force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/HRCSVC21_Parts_Order_Integration_Details__mdt.object-meta.xml
<CustomObject>
    <description>SE-2784:As an agent creating a parts order from desktop, I need the ability to enter a ship-to and see the sold-to returned from JDE. I need to be able to override the sold-to location as well as enter a ship-to address override</description>
    <label>Parts Order Integration Detail</label>
    <pluralLabel>Parts Order Integration Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_Client_Id__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Client_Id__c</fullName>
    <description>SE-2784/2780/2465 - Used for integration between JDE and Salesforce</description>
    <label>Client Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Client_Secret__c</fullName>
    <description>SE-2784/2780/2465 - Used for integration between JDE and Salesforce</description>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_Content_Type__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Content_Type__c</fullName>
    <description>SE-2784</description>
    <label>Content-Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_Method__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Method__c</fullName>
    <description>SE-2784</description>
    <label>Method</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_URL__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_URL__c</fullName>
    <description>SE-2784/2780/2465 - Used for integration between JDE and Salesforce</description>
    <label>URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_X_Correlation_ID__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_X_Correlation_ID__c</fullName>
    <description>SE-2784/2780/2465 - Used for integration between JDE and Salesforce</description>
    <label>Transit Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/HRCSVC20_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_Business_Unit__c</fullName>
    <description>Business unit determined based on ship to customer location country. Needed for integration to JDE</description>
    <formula>CASE( TEXT( HRCSVC_Ship_To_Location__r.HRCFSL_Country__c ), &apos;US&apos;, &apos;99635&apos;, &apos;CA&apos;, &apos;99662&apos;, &apos;99635&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HRCSVC20_Pricing_Processing_Version__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_Pricing_Processing_Version__c</fullName>
    <description>Processing Version determined based on ship to customer country. Needed for JDE integration</description>
    <formula>CASE( TEXT( HRCSVC_Ship_To_Location__r.HRCFSL_Country__c ), &apos;US&apos;, &apos;HRC0005A&apos;, &apos;CA&apos;, &apos;HRC0038A&apos;, &apos;HRC0005A&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricing Processing Version</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HRCSVC20_Sold_To_Location__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_Sold_To_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SE-1914:Update Field Names on Parts Order - New field to lookup to Location (Service Cloud 2.1)</description>
    <label>Sold To</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Orders (Sold To Location)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HRCSVC21_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Error_Message__c</fullName>
    <description>Field to display any integration error messages</description>
    <label>Integration Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HRCSVC_Ship_To_Location__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC_Ship_To_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To (Location)</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>ORLI-{0}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/HRCSVC20_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/HRCSVC21_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Error_Message__c</fullName>
    <description>Field to display any integration error messages</description>
    <label>Integration Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.HRCFSL_JDE_CostCenter__c</field>
            <operation>equals</operation>
            <value>99635</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HRCSVC21_Get_Pricing.cls
/*********************************************************************************************************************************************
* Trigger Name: HRCSVC21_Get_Pricing
* Author: Capgemini
* Date: Nov/21/2021
*********************************************************************************************************************************************/
public class HRCSVC21_Get_Pricing {
    public static  Boolean flag;
    public static List<Order_Line_Item__c> OliList=new List<Order_Line_Item__c>();
    public static  List<String> Message;
    public static  String orderID;
    public static  String passingIds(List<String> allIds){
        Message= new list<String>();
        try{
            flag=true;
            for(String record:allIds){
                if(record.length()==18){
                    system.debug('richa'+record.length());
                    system.debug(' before times????');
                    Order_Line_Item__c oli = new Order_Line_Item__c ();
                   oli = requestPricingitem((id)record,true);
                   if(oli != null)
                  OliList.add(oli);
                   // OliList.add(requestPricingitem((id)record,true));
                    system.debug('times????');
                } 
            }  if(!OliList.isEmpty()){
                update OliList;
                // Order_Line_Item__c oli=[select Order__c from Order_Line_Item__c where id=]
                if(Message.size() == 0){
                    Message.add(orderID);
                }            
                system.debug('Message'+Message);   
            }
        }catch(Exception e){
         Message.add('Error!');  
        }
        return Message[0];
    } 
    public static  Order_Line_Item__c requestPricingitem(Id oliId,Boolean isflag) {
        Order_Line_Item__c oli = new Order_Line_Item__c ();
      
        try{  
            //String orderid;
            Map<String, HRCSVC21_Parts_Order_Integration_Details__mdt> mapEd = HRCSVC21_Parts_Order_Integration_Details__mdt.getAll();
            oli = [Select id, Order__c, Order__r.HRCSVC20_Business_Unit__c,name, Order__r.HRCSVC20_Pricing_Processing_Version__c, Order__r.HRCSVC_Ship_To_Location__r.HRCFSL_Customer_ID__c,Product__r.HRCFSL_Parts_Number__c,
                   Order__r.HRCSVC20_Sold_To_Location__r.HRCFSL_Customer_ID__c,HRCSVC20_Unit_Price__c, HRCSVC21_Error_Message__c from Order_Line_Item__c where id = :oliId LIMIT 1];
            orderID=oli.Order__c;
            system.debug('sold to id: ' + oli.order__r.HRCSVC20_Sold_To_Location__r.HRCFSL_Customer_ID__c);
            Http http = new Http(); 
            HttpRequest request = new HttpRequest();
            request.setHeader('clientid',(String) mapEd.get('HRCSVC21_Get_Unit_Price').HRCSVC21_Client_Id__c);
            request.setHeader('clientsecret', mapEd.get('HRCSVC21_Get_Unit_Price').HRCSVC21_Client_Secret__c);
            request.setHeader('X-Correlation-ID', mapEd.get('HRCSVC21_Get_Unit_Price').HRCSVC21_X_Correlation_ID__c);
            request.setHeader('Content-Type',mapEd.get('HRCSVC21_Get_Unit_Price').HRCSVC21_Content_Type__c);
            String endpoint = mapEd.get('HRCSVC21_Get_Unit_Price').HRCSVC21_URL__c+'?soldToEntityId='+oli.Order__r.HRCSVC20_Sold_To_Location__r.HRCFSL_Customer_ID__c+'&businessUnit='+oli.Order__r.HRCSVC20_Business_Unit__c+'&processingVersion='+oli.Order__r.HRCSVC20_Pricing_Processing_Version__c+'&shipToEntityId='+oli.Order__r.HRCSVC_Ship_To_Location__r.HRCFSL_Customer_ID__c+'&partsNumber='+oli.Product__r.HRCFSL_Parts_Number__c+'';
            //system.debug('endpoint1'+endpoint);
           // String endpoint = mapEd.get('HRCSVC21_Get_Unit_Price').HRCSVC21_URL__c+'?soldToEntityId=600077&businessUnit=99635&processingVersion=HRC0005A&shipToEntityId=600077&partsNumber=P2217A';
            system.debug('endpoint'+endpoint);
            request.setEndpoint(endpoint);
            request.setMethod(mapEd.get('HRCSVC21_Get_Unit_Price').HRCSVC21_Method__c);
            request.setTimeout(120000);
            system.debug('setBody====>>>'+request.getBody());
            HttpResponse response = Http.send(request);
            String result=response.getBody();
            System.debug('resultresult'+JSON.serializePretty(result));
            if(response.getStatusCode() == 200){      
                Map<String, String> mapOrd = (Map<String, String>) JSON.deserialize(result, Map<String, String>.class);
                String unitprice= mapOrd.get('priceUnit');
                String curCode = mapOrd.get('currencyCode');
                oli.HRCSVC20_Unit_Price__c=decimal.valueOf(unitprice);
                oli.CurrencyIsoCode = curCode;
                if(oli.HRCSVC21_Error_Message__c != NULL){
                    oli.HRCSVC21_Error_Message__c = NULL;
                }              
            }
            else{
                Map<String, Object> mapJSON = (Map<String, Object>) JSON.deserializeUntyped(result);
                Map<String, Object> errors = (Map<String, Object>)mapJSON.get('error');
                String errorMessage = String.valueOf(errors.get('message'));
                oli.HRCSVC21_Error_Message__c = errorMessage;
                Message.add(oli.Id);
            }
            return oli;
            // oli.HRCSVC20_Unit_Price__c=decimal.valueOf('200');
            /*if(isflag){
                OliList.add(oli);
                }*/
        }catch(Exception e){
            system.debug('error'+e.getMessage()+e.getLineNumber()+e.getStackTraceString());
            oli=null;
            return oli;
        } 
        
    }
}