force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/HRCSVC21_Parts_Order_Integration_Details__mdt.object-meta.xml
<CustomObject>
    <description>SE-2784:As an agent creating a parts order from desktop, I need the ability to enter a ship-to and see the sold-to returned from JDE. I need to be able to override the sold-to location as well as enter a ship-to address override</description>
    <label>Parts Order Integration Detail</label>
    <pluralLabel>Parts Order Integration Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_Client_Id__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Client_Id__c</fullName>
    <description>SE-2784/2780/2465 - Used for integration between JDE and Salesforce</description>
    <label>Client Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Client_Secret__c</fullName>
    <description>SE-2784/2780/2465 - Used for integration between JDE and Salesforce</description>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_Content_Type__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Content_Type__c</fullName>
    <description>SE-2784</description>
    <label>Content-Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_Method__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Method__c</fullName>
    <description>SE-2784</description>
    <label>Method</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_URL__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_URL__c</fullName>
    <description>SE-2784/2780/2465 - Used for integration between JDE and Salesforce</description>
    <label>URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC21_Parts_Order_Integration_Details__mdt/fields/HRCSVC21_X_Correlation_ID__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_X_Correlation_ID__c</fullName>
    <description>SE-2784/2780/2465 - Used for integration between JDE and Salesforce</description>
    <label>Transit Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/HRCSVC20_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_Business_Unit__c</fullName>
    <description>Business unit determined based on ship to customer location country. Needed for integration to JDE</description>
    <formula>CASE( TEXT( HRCSVC_Ship_To_Location__r.HRCFSL_Country__c ), &apos;US&apos;, &apos;99635&apos;, &apos;CA&apos;, &apos;99662&apos;, &apos;99635&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HRCSVC20_Pricing_Processing_Version__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_Pricing_Processing_Version__c</fullName>
    <description>Processing Version determined based on ship to customer country. Needed for JDE integration</description>
    <formula>CASE( TEXT( HRCSVC_Ship_To_Location__r.HRCFSL_Country__c ), &apos;US&apos;, &apos;HRC0005A&apos;, &apos;CA&apos;, &apos;HRC0038A&apos;, &apos;HRC0005A&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricing Processing Version</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HRCSVC21_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Error_Message__c</fullName>
    <description>Field to display any integration error messages</description>
    <label>Integration Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HRCSVC_Ship_To_Location__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC_Ship_To_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To (Location)</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>ORLI-{0}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/HRCSVC20_Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_Available_Quantity__c</fullName>
    <description>Available Quantity of a part returned by Inventory check integration to JDE. SE-2780</description>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/HRCSVC21_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_Error_Message__c</fullName>
    <description>Field to display any integration error messages</description>
    <label>Integration Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.HRCFSL_JDE_CostCenter__c</field>
            <operation>equals</operation>
            <value>99635</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HRCSVC21_InventoryCheckHandler.cls
/*****************************************************************************************************
* Name                             : HRCSVC21_InventoryCheckHandler
* Author                           : Capgemini
* Date                             : November/24/2021
* Requirement/Project Name         : Hill-Rom
* Requirement/Project Description  : Class to do apex callout to JDE to fetch product quantity from inventory 
                                     and parse the response to update Order_Line_Item__c.HRCSVC20_Available_Quantity__c 
                                     #SE-2780 (Service Cloud 2.1)
* Revison                          :
*****************************************************************************************************/

global class HRCSVC21_InventoryCheckHandler {
          
    global class inputValue
    {
        @InvocableVariable(required=true)
        global Id recordId;
        
    }
    global class returnmessage
    {
        @InvocableVariable
        global string succerrmsg;
    } 
    
    @InvocableMethod(label='Get Available Quantity' description='Get available quantity on oli')
    
    public static List<returnmessage>UpdateorderLines(List<Id> recordId)

    {   
        
        returnmessage returnresults = new returnmessage();
        List<returnmessage> Output =new  List<returnmessage>();
        try{
        List<Order_Line_Item__c> oliList = [SELECT Id,Product__c,HRCSVC20_Available_Quantity__c,order__r.id,Order__r.HRCSVC_Ship_To_Location__r.HRCFSL_Customer_ID__c,Order__r.HRCSVC20_Business_Unit__c,Order__r.HRCSVC20_Pricing_Processing_Version__c,Product__r.HRCFSL_Parts_Number__c FROM Order_Line_Item__c WHERE Order__r.id =:recordId]; 
        system.debug('olilist :---->>>>>>>' +oliList);
        
        List<Id> OLIId = new List<Id>();
       
        for( Order_Line_Item__c olc: oliList){
            if(olc.Product__c!=null){
                OLIId.add(olc.id);
            }
        }
        
        
        if(!OLIId.isEmpty()){
             
           returnresults = new returnmessage();
            returnresults.succerrmsg= getavailablequantity(OLIId);
            Output.add(returnresults);
           
        }  
      
        }
        catch(exception e){
            returnresults = new returnmessage();
            returnresults.succerrmsg='Processing Problem';
            Output.add(returnresults);
        }
        system.debug('output value' +Output);
        return Output;
        
    } 
    
    public static string getavailablequantity(List<Id> oliIdnew){
        
      String succerrmessage;
      String result; 
        try{
            List<Order_Line_Item__c> OliUpdatedList = New list <Order_Line_Item__c>();
            For(id OLI:oliIdnew ){
                Order_Line_Item__c olinew = new Order_Line_Item__c();
                olinew = requestavailablequantity(OLI);
                if(olinew !=null){
                    OliUpdatedList.add(olinew);
                }
                
             
            } 
            if(!OliUpdatedList.isEmpty()){
                update OliUpdatedList;
                result = System.label.HRCSVC20_product_availability_success_message;
            }
            else{
                result = System.label.HRCSVC20_product_nonavailability_error_message;
            }
            succerrmessage= result ;
        }
        
        catch(exception e)
        {
           
          result = System.label.HRCSVC20_product_nonavailability_error_message;
          succerrmessage = result;
            
        } 
        
        return succerrmessage;
    }
    
    public static Order_Line_Item__c requestavailablequantity(Id oliIdnew) {
        Order_Line_Item__c oli = new Order_Line_Item__c ();
        try{
        Map<String, HRCSVC21_Parts_Order_Integration_Details__mdt> mapEd = HRCSVC21_Parts_Order_Integration_Details__mdt.getAll();
        System.debug('MapEd values-->'+Json.serializePretty(mapEd.get('HRCSVC21_Inventory')));
        
        oli = [Select id,Product__c,HRCSVC20_Available_Quantity__c,order__r.id,Order__r.HRCSVC_Ship_To_Location__r.HRCFSL_Customer_ID__c,Order__r.HRCSVC20_Business_Unit__c,Order__r.HRCSVC20_Pricing_Processing_Version__c,Product__r.HRCFSL_Parts_Number__c,HRCSVC21_Error_Message__c from Order_Line_Item__c where id = :oliIdnew LIMIT 1];
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setHeader('client_id',(String) mapEd.get('HRCSVC21_Inventory').HRCSVC21_Client_Id__c);
        request.setHeader('client_secret', mapEd.get('HRCSVC21_Inventory').HRCSVC21_Client_Secret__c);
        request.setHeader('X-Correlation-ID', mapEd.get('HRCSVC21_Inventory').HRCSVC21_X_Correlation_ID__c);
        request.setHeader('Content-Type',mapEd.get('HRCSVC21_Inventory').HRCSVC21_Content_Type__c);
        //String endpoint = mapEd.get('HRCSVC21_Inventory').HRCSVC21_URL__c+'?businessUnit=99635&processingVersion=HRC0005A&shipToEntityId=3200864&partsNumber=159964';
        String endpoint = mapEd.get('HRCSVC21_Inventory').HRCSVC21_URL__c+'?shipToEntityId='+oli.Order__r.HRCSVC_Ship_To_Location__r.HRCFSL_Customer_ID__c+'&businessUnit='+oli.Order__r.HRCSVC20_Business_Unit__c+'&processingVersion='+oli.Order__r.HRCSVC20_Pricing_Processing_Version__c+'&partsNumber='+oli.Product__r.HRCFSL_Parts_Number__c+'';
        request.setEndpoint(endpoint);
            system.debug('Endpoint' +endpoint);
        request.setMethod(mapEd.get('HRCSVC21_Inventory').HRCSVC21_Method__c);
        request.setTimeout(120000); 
        
        
        system.debug('setBody====>>>'+request.getBody());
        HttpResponse response = Http.send(request);
        String result=response.getBody();
        System.debug('Recieved Body Data======>>>'+JSON.serializePretty(result));
                  
            if(response.getStatusCode() == 200){
                Map<String, String> mapOrd = (Map<String, String>) JSON.deserialize(result, Map<String, String>.class); //Deserializing using Map to fetch 'Available Quantity' value from the response body
                String AvailableQuantity = mapOrd.get('quantityAvailable');
                System.debug('quantity available: ' + AvailableQuantity); 
                System.debug('resultresult'+result);
                Integer AvailQuantity = Integer.valueOf(AvailableQuantity);
                if(AvailQuantity < 0){
                    AvailQuantity = 0;
                }
                oli.HRCSVC20_Available_Quantity__c = AvailQuantity;
                if(oli.HRCSVC21_Error_Message__c != NULL){
                    oli.HRCSVC21_Error_Message__c = NULL;
                }
            }
            else{
                Map<String, Object> mapJSON = (Map<String, Object>) JSON.deserializeUntyped(result);
                Map<String, Object> errors = (Map<String, Object>)mapJSON.get('error');
                String errorMessage = String.valueOf(errors.get('message'));
                oli.HRCSVC21_Error_Message__c = errorMessage;
            }
        return oli;
    }
    
    catch(exception e)
    {
        system.debug('error- '+e.getMessage()+e.getStackTraceString());
        oli = [Select Id, HRCSVC21_Error_Message__c FROM Order_Line_Item__c WHERE id = :oliIdnew];
        oli.HRCSVC21_Error_Message__c = e.getMessage();
        return oli;
    }
       
    } 
   
}