force-app/main/default/objects/Evaluation_Form__c/Evaluation_Form__c.object-meta.xml
<CustomObject>
    <label>Evaluation Form</label>
    <nameField>
        <displayFormat>EvalForm-{000000}</displayFormat>
        <label>Evaluation Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluation_Form__c/fields/Deliver_To__c.field-meta.xml
<CustomField>
    <fullName>Deliver_To__c</fullName>
    <label>Deliver To</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Service Center</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evaluation_Form__c/fields/Evaluation_Blanket_Agreement_Completed__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Blanket_Agreement_Completed__c</fullName>
    <label>Evaluation Blanket Agreement Completed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evaluation_Form__c/fields/N_C_PO_required__c.field-meta.xml
<CustomField>
    <fullName>N_C_PO_required__c</fullName>
    <label>N/C PO Required?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evaluation_Form__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Evaluation Forms</relationshipLabel>
    <relationshipName>Evaluation_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evaluation_Form__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Evaluation Forms</relationshipLabel>
    <relationshipName>Evaluation_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evaluation_Form__c/fields/RDC_Location__c.field-meta.xml
<CustomField>
    <fullName>RDC_Location__c</fullName>
    <label>Pickup RDC Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Dallas</fullName>
            </value>
            <value>
                <fullName>Bell</fullName>
            </value>
            <value>
                <fullName>Pennsauken</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Charleston</fullName>
            </value>
            <value>
                <fullName>Cincinnati</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evaluation_Form__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evaluation_Form__c/fields/Rqst_Date_of_Delivery_to_Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Rqst_Date_of_Delivery_to_Service_Center__c</fullName>
    <label>Rqst Date of Delivery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Products_Requested__c/Products_Requested__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Products_Requested__c/fields/Evaluation_Form__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Form__c</fullName>
    <label>Evaluation Form</label>
    <referenceTo>Evaluation_Form__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Products_Requested__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Frames</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>LIKO Accessories</fullName>
            </value>
            <value>
                <fullName>LIKO lifts</fullName>
            </value>
            <value>
                <fullName>Patient Monitoring/CFCM</fullName>
            </value>
            <value>
                <fullName>Surfaces</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApproverUpdate_Test.cls
@isTest(seealldata=true)
private class ApproverUpdate_Test {


    static testMethod void runTest() {
    Date MyDate = date.newinstance(2012,11,17);
    //string name = [SELECT name FROM Userrole WHERE parentroleid != null and name like 'Account Exe%' limit 1].name;
    //User u1 = [SELECT Id FROM User WHERE Userrole.name=:name limit 1];
    User u1 = [SELECT Id FROM User WHERE Profile.name = 'HRC Account Executive' and isactive = true and userrole.parentroleid != null and createddate < last_n_months:3 limit 1];
            
       // Run As U1
        System.RunAs(u1){
    id newid = [select id from contact limit 1].id;
    system.debug('contactid'+newid);
   id oppid = [select id from opportunity where CRS_OMS_CA__c != null limit 1].id;
       Evaluation_Form__c ef 
         = new Evaluation_Form__c(RDC_location__c = 'Pennsauken',opportunity__c = oppid, Deliver_To__c = 'Customer', N_C_PO_required__c = 'no', Evaluation_Blanket_Agreement_Completed__c = 'yes', 
                                          Rqst_Date_of_Delivery_to_Service_Center__c = mydate,Primary_Contact__c = newid);
       insert ef;   
       
        Products_Requested__c  pr
         = new Products_Requested__c (evaluation_form__C = ef.id, Product_type__C = 'frames',quantity__c = 10);                
       insert pr;
              Evaluation_Form__c ef1 
         = new Evaluation_Form__c(RDC_location__c = 'Chicago',opportunity__c = oppid, Deliver_To__c = 'Customer', N_C_PO_required__c = 'no', Evaluation_Blanket_Agreement_Completed__c = 'yes', 
                                          Rqst_Date_of_Delivery_to_Service_Center__c = mydate,Primary_Contact__c = newid,record_id__c = ef.id);
       insert ef1; 
       ef.RDC_location__c = 'Atlanta';
       update ef;
       ef1.RDC_location__c = 'Dallas';
       update ef1;
      /** Account a = new Account(Name = 'x', JDE_Record_Type__c = 'FACx');
       try{
          insert a;
       }
       catch(Exception e){}**/
    }
}
}