force-app/main/default/objects/Additional_Account_Info__c/Additional_Account_Info__c.object-meta.xml
<CustomObject>
    <description>Contains additional Account Information for Trumpf Sales Team use</description>
    <label>Additional Account Info</label>
    <nameField>
        <label>Additional Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Account Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Account_Info__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Additional Account Info</relationshipLabel>
    <relationshipName>Additional_Account_Info1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Account_Info__c/fields/Document_Store_Error__c.field-meta.xml
<CustomField>
    <fullName>Document_Store_Error__c</fullName>
    <description>Used to store Error Messages from Mulesoft for the Care Comm SharePoint integration.</description>
    <label>Document Store Error</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Additional_Account_Info__c/fields/Document_Store_Link__c.field-meta.xml
<CustomField>
    <fullName>Document_Store_Link__c</fullName>
    <description>Used by the Care Comm SharePoint Integration for the Document Store.</description>
    <label>Document Store Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Additional_Account_Info__c/recordTypes/Document_Store.recordType-meta.xml
<RecordType>
    <fullName>Document_Store</fullName>
    <active>true</active>
    <description>Used to manage the Care Comm Document Store SharePoint integration.</description>
    <label>Document Store</label>
</RecordType>

force-app/main/default/classes/SharepointAPIIntegration.cls
public class SharepointAPIIntegration {
	@AuraEnabled
    public static String doCallout(String accountId){
        List<Additional_Account_Info__c> existingAccountInfoList = new List<Additional_Account_Info__c>();
        existingAccountInfoList = [Select Id from Additional_Account_Info__c where Account__c = :accountId AND Document_Store_Link__c !=null ];
        if(existingAccountInfoList.size() > 0){
            return 'Sharepoint link already exist';
        }
        String returnValue = '';
        try{
            HttpRequest req = new HttpRequest();
            req.setEndpoint('callout:Document_Store?parentFolder='+accountId+'&childFolder='+System.Label.Sharepoint_Child_Folders);
            req.setHeader('X-Correlation-ID', '1234');
            req.setHeader('client_id', '{!$Credential.UserName}');
            req.setHeader('client_secret', '{!$Credential.Password}');
            req.setHeader('Content-Type', 'application/json;charset=UTF-8');
            req.setMethod('GET');
            req.setTimeout(120000); //120000
            Http http = new Http();
            HTTPResponse res = http.send(req);
            STring documentTypeId = Schema.SObjectType.Additional_Account_Info__c.getRecordTypeInfosByName().get('Document Store').getRecordTypeId();
            if(res.getStatus() == 'OK' && res.getStatusCode() == 200){
                List<Additional_Account_Info__c> accountInfoList = [Select id from Additional_Account_Info__c where Document_Store_Link__c = null AND Account__c = :accountId AND Name = 'Document Store Error' And recordTypeId = :documentTypeId];
                if(accountInfoList.size() > 0){
                    delete accountInfoList;
                }
                Additional_Account_Info__c accountInfo = new Additional_Account_Info__c();
                if(!Test.isRunningTest()){
                	accountInfo.Account__c = accountId;
                }
                accountInfo.Name = 'Document Store';
                accountInfo.RecordTypeId = Schema.SObjectType.Additional_Account_Info__c.getRecordTypeInfosByName().get('Document Store').getRecordTypeId();
                accountInfo.Document_Store_Link__c = System.Label.Sharepoint_Link + accountId;
                
                insert accountInfo;
                returnValue = 'success';
            }
            else if(res.getStatusCode() != 200){
                Additional_Account_Info__c accountInfo = new Additional_Account_Info__c();
                accountInfo.Account__c = accountId;
                accountInfo.Name = 'Document Store Error';
                accountInfo.RecordTypeId = Schema.SObjectType.Additional_Account_Info__c.getRecordTypeInfosByName().get('Document Store').getRecordTypeId();
                accountInfo.Document_Store_Error__c = 'Response Status: ' + res.getStatus() + 'Response code : '+res.getStatusCode() + ' ' + res.getBody();
                insert accountInfo;
                returnValue = 'error';
            }
            return returnValue;
        }
        catch(Exception e){
            Additional_Account_Info__c accountInfo = new Additional_Account_Info__c();
            accountInfo.Account__c = accountId;
            accountInfo.Name = 'Document Store Error';
            accountInfo.RecordTypeId = Schema.SObjectType.Additional_Account_Info__c.getRecordTypeInfosByName().get('Document Store').getRecordTypeId();
            accountInfo.Document_Store_Error__c = 'Error Message: ' + e.getMessage();
            insert accountInfo;
            returnValue = 'error';
            return returnValue;
        }
    }
}