force-app/main/default/objects/Capital_Iem__c/Capital_Iem__c.object-meta.xml
<CustomObject>
    <description>CFR Database - to store Investment details</description>
    <label>Capital Item</label>
    <nameField>
        <displayFormat>CI-{00000000}</displayFormat>
        <label>Capital Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Capital_Iem__c/fields/Capital_Item__c.field-meta.xml
<CustomField>
    <fullName>Capital_Item__c</fullName>
    <description>Capital Item Details</description>
    <label>Capital Item</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Capital_Iem__c/fields/Capital_Request__c.field-meta.xml
<CustomField>
    <fullName>Capital_Request__c</fullName>
    <label>Capital Request</label>
    <referenceTo>Capital_Requests__c</referenceTo>
    <relationshipName>Capital_Iems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Capital_Iem__c/fields/Original__c.field-meta.xml
<CustomField>
    <fullName>Original__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Capital Iem Original Amount</description>
    <label>Original</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/Capital_Requests__c.object-meta.xml
<CustomObject>
    <description>CFR Database</description>
    <label>Capital Request</label>
    <nameField>
        <displayFormat>REQ-{000000}</displayFormat>
        <label>Capital Requests Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Capital_Requests__c/fields/Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for representing approver in Approval process</description>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Capital_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Approver_2__c.field-meta.xml
<CustomField>
    <fullName>Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for representing approver in Approval process</description>
    <label>Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Capital_Requests4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Approver_3__c.field-meta.xml
<CustomField>
    <fullName>Approver_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for representing approver in Approval process</description>
    <label>Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Capital_Requests5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Approver_4__c.field-meta.xml
<CustomField>
    <fullName>Approver_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for representing approver in Approval process</description>
    <label>Approver 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Capital_Requests6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Auto_Approve_Step_HelperField__c.field-meta.xml
<CustomField>
    <fullName>Auto_Approve_Step_HelperField__c</fullName>
    <label>Auto Approve Step HelperField</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Executive_Summary__c.field-meta.xml
<CustomField>
    <fullName>Executive_Summary__c</fullName>
    <inlineHelpText>You can copy and paste text and add an image to create a master summary.</inlineHelpText>
    <label>Executive Summary</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/InitiateAutoApproveProcess__c.field-meta.xml
<CustomField>
    <fullName>InitiateAutoApproveProcess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>InitiateAutoApproveProcess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Last_Approved_Step__c.field-meta.xml
<CustomField>
    <fullName>Last_Approved_Step__c</fullName>
    <description>Picklist to hold the step number of Last Approved step in Approval Process</description>
    <label>Last Approved Step</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>Name of the project</description>
    <label>Project Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Project_Objective__c.field-meta.xml
<CustomField>
    <fullName>Project_Objective__c</fullName>
    <label>Strategic Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>New Product/Market Expansion</fullName>
            </value>
            <value>
                <fullName>Cost Reduction</fullName>
            </value>
            <value>
                <fullName>Core/Base</fullName>
            </value>
            <value>
                <fullName>Profit Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Routed for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Spend in Progress</fullName>
            </value>
            <value>
                <fullName>Closure in Process</fullName>
            </value>
            <value>
                <fullName>Closure Approval</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Item__c/Expense_Item__c.object-meta.xml
<CustomObject>
    <description>CFR Database - to store Investment details</description>
    <label>Expense Item</label>
    <nameField>
        <displayFormat>EI-{00000000}</displayFormat>
        <label>Expense Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/fields/Capital_Request__c.field-meta.xml
<CustomField>
    <fullName>Capital_Request__c</fullName>
    <label>Capital Request</label>
    <referenceTo>Capital_Requests__c</referenceTo>
    <relationshipLabel>Expense Items</relationshipLabel>
    <relationshipName>Expense_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Expense_Item__c.field-meta.xml
<CustomField>
    <fullName>Expense_Item__c</fullName>
    <label>Expense Item</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Original__c.field-meta.xml
<CustomField>
    <fullName>Original__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Original</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/HRCCFR_TestSetupData.cls
/******************************************************************************************************* 
Class       :   HRCCFR_TestSetupData
Description :   Utility class for providing test data related to CFR App.

*******************************************************************************************************/
@isTest
public class HRCCFR_TestSetupData {
    
    //   Method to create a User record
    public static User createUser(Profile prof, string uniqueSuffix){
         Integer randomInteger = Integer.valueOf(math.rint(math.random()*1000000));
        User userRec = new User(UserName            = 'user_'+ uniqueSuffix + randomInteger +'@hill-rom.com' ,                              
                                JDE_External_Id__c  = 'CFR'+ uniqueSuffix,
                                LastName            = 'test_ ' + uniqueSuffix, 
                                Email               = 'user_' + uniqueSuffix + '@hill-rom.com', 
                                Alias               = 'user_ ' + uniqueSuffix,
                                CommunityNickname   = 'test_' + uniqueSuffix,
                                TimeZoneSidKey      = 'America/Los_Angeles', 
                                LocaleSidKey        = 'en_US', 
                                EmailEncodingKey    = 'UTF-8', 
                                ProfileId           = prof.Id,
                                LanguageLocaleKey   = 'en_US', 
                                isActive                = true
                            );      
        return userRec;
    }
   
    //  Method to create a User record
    public static User getUser(string profileName){
        User userRec = [select id, Username, LastName, Email, Alias, CommunityNickname, TimeZoneSidKey, LocaleSidKey, 
                        EmailEncodingKey, ProfileId, LanguageLocaleKey from user where profile.name = :profileName limit 1];
        return userRec;
    }
    
    
    //Method to fetch profile
    public static Profile getProfile(String profileName){
        Profile userProfile = [ Select Id From Profile Where Name = :ProfileName limit 1 ];
        return userProfile; 
    }
    
    //Method to create a Capital Request
    public static Capital_Requests__c createCapitalRequest(Id recordType, String name){
        Capital_Requests__c cr = new Capital_Requests__c(recordTypeID = recordType, 
                                                        Executive_Summary__c='test', 
                                                        Project_Name__c= name,
                                                        Project_Objective__c = 'test');
        //insert cr;
        return cr;
    }
    
    //Method to fetch Capital Request record
    public static Capital_Requests__c getCapitalRequest(String Name){
        try{
            Capital_Requests__c cr = [select Name,Status__c,Last_Approved_Step__c,InitiateAutoApproveProcess__c,
                                             Auto_Approve_Step_HelperField__c, Approver_1__c, Approver_2__c,
                                             Approver_3__c, Approver_4__c 
                                      from Capital_Requests__c where Project_Name__c=: Name limit 1];
            return cr;
        }catch(Exception e){
            return null;
        }
    }
    
    //Method to create a Capital_Iem__c
    public static Capital_Iem__c createCapitalItem(Id capitalRequestId, integer amount){
        Capital_Iem__c cr = new Capital_Iem__c(Capital_Request__c = capitalRequestId, 
                                               Original__c = amount,
                                               Capital_Item__c = 'test Capital Item');
        
        return cr;
    }
    
    //Method to fetch Capital_Iem__c record
    public static Capital_Iem__c getCapitalItem(String crName){
        try{
            Capital_Iem__c cr = [select Name from Capital_Iem__c where Name =: crName limit 1];
            return cr;
        }catch(Exception e){
            return null;
        }
    }
    
    //Method to create a Expense_Item__c
    public static Expense_Item__c createExpenseItem(Id capitalRequestId, integer amount){
        Expense_Item__c cr = new Expense_Item__c(Expense_Item__c = capitalRequestId, 
                                                 Original__c = amount);
        
        return cr;
    }
    
    //Method to fetch Capital_Iem__c record
    public static Expense_Item__c getExpenseItem(String crName){
        try{
            Expense_Item__c cr = [select Name from Expense_Item__c where Name =: crName limit 1];
            return cr;
        }catch(Exception e){
            return null;
        }
    }
   /** 
    //Method to fetch Capital_Iem__c record
    public static List<HRCCFR_Capital_ApprovalStep_Queue_pair> getCapitalCustomSetting(){
       //HRCCFR_Capital_ApprovalStep_Queue_pair = new HRCCFR_Capital_ApprovalStep_Queue_pair();
       
    }
    **/
    
}//End Class