force-app/main/default/objects/Capital_Requests__c/Capital_Requests__c.object-meta.xml
<CustomObject>
    <description>CFR Database</description>
    <label>Capital Request</label>
    <nameField>
        <displayFormat>REQ-{000000}</displayFormat>
        <label>Capital Requests Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Capital_Requests__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>Name of the project</description>
    <label>Project Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Supplemental__c.field-meta.xml
<CustomField>
    <fullName>Supplemental__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Supplemental</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Supplemental_Check__c.field-meta.xml
<CustomField>
    <fullName>Supplemental_Check__c</fullName>
    <formula>IF( Total_Supplemental_Amount__c  &gt; 0 , true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplemental</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HRC_CFR_SupplementalInvokeAPI.cls
public class HRC_CFR_SupplementalInvokeAPI {
	@InvocableMethod
    public static void invokeapexcallout(list<Capital_Requests__c> capitalReqData) {
        system.debug('capitalReqData====>>>'+capitalReqData);
        //if(!System.isFuture() && !System.isBatch()){
           //HRC_CapitalRequestAPI.apexcalloutSupplemental(capitalReqData[0].Supplemental__c,capitalReqData[0].Project_Name__c,capitalReqData[0].id);
           HRC_CapitalRequestAPI.apexcalloutSupplemental(capitalReqData[0].Supplemental_Check__c,capitalReqData[0].Project_Name__c,capitalReqData[0].id);
        //}
    }
}