force-app/main/default/objects/Capital_Requests__c/Capital_Requests__c.object-meta.xml
<CustomObject>
    <description>CFR Database</description>
    <label>Capital Request</label>
    <nameField>
        <displayFormat>REQ-{000000}</displayFormat>
        <label>Capital Requests Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Capital_Requests__c/fields/Is_this_a_Physical_Asset__c.field-meta.xml
<CustomField>
    <fullName>Is_this_a_Physical_Asset__c</fullName>
    <label>Is this a Physical Asset?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>Name of the project</description>
    <label>Project Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/SAP_CFR_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_CFR_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP CFR Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Routed for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Spend in Progress</fullName>
            </value>
            <value>
                <fullName>Closure in Process</fullName>
            </value>
            <value>
                <fullName>Closure Approval</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Supplemental__c.field-meta.xml
<CustomField>
    <fullName>Supplemental__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Supplemental</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HRC_CFR_CalloutTestAPI.cls
@isTest
public class HRC_CFR_CalloutTestAPI {
    private static List<Capital_Requests__c> lstCapitalRequest;
    @isTest static  void testGetCallout() {
        Capital_Requests__c cfrDataTest = new Capital_Requests__c();
        cfrDataTest.Status__c='Approved';
        cfrDataTest.Project_Name__c='TestingProject';
        cfrDataTest.Company_code__c='5000';
        cfrDataTest.Is_this_a_Physical_Asset__c='Yes';
        insert cfrDataTest;
        
        List<Capital_Requests__c> lstData = new List<Capital_Requests__c>();
		lstData.add(cfrDataTest);
        Test.startTest();
        	Test.setMock(HttpCalloutMock.class, new HRC_CFR_CalloutTest()); 
        	HRC_CapitaRequestInvokeAPI.invokeapexcallout(lstData);
        Test.stopTest();
    }
    
    
    
    @isTest static  void testGetCalloutForSupplemental() {
        Capital_Requests__c cfrDataTest = new Capital_Requests__c();
        cfrDataTest.Status__c='Approved';
        cfrDataTest.Project_Name__c='TestingProject';
        cfrDataTest.Supplemental__c=True;
        cfrDataTest.SAP_CFR_Number__c='5000-CP-0094';
        cfrDataTest.Company_code__c='5000';
        cfrDataTest.Is_this_a_Physical_Asset__c='Yes';
        insert cfrDataTest;
        
        List<Capital_Requests__c> lstData = new List<Capital_Requests__c>();
		lstData.add(cfrDataTest);
        Test.startTest();
        	Test.setMock(HttpCalloutMock.class, new HRC_CFR_CalloutTest()); 
        	HRC_CFR_SupplementalInvokeAPI.invokeapexcallout(lstData);
        Test.stopTest();
    }
}