force-app/main/default/objects/Capital_Requests__c/Capital_Requests__c.object-meta.xml
<CustomObject>
    <description>CFR Database</description>
    <label>Capital Request</label>
    <nameField>
        <displayFormat>REQ-{000000}</displayFormat>
        <label>Capital Requests Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Capital_Requests__c/fields/Financial_Analyst__c.field-meta.xml
<CustomField>
    <fullName>Financial_Analyst__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Add the appropriate Financial Analyst for your Business.</description>
    <inlineHelpText>Add the appropriate Financial Analyst for your Business.</inlineHelpText>
    <label>Financial Analyst</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Capital_RequestszsQe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Key_Assumptions__c.field-meta.xml
<CustomField>
    <fullName>Key_Assumptions__c</fullName>
    <label>Key Assumptions</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>Name of the project</description>
    <label>Project Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Rejection_Comments_Required__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Comments_Required__c</fullName>
    <label>Rejection Comments Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capital_Requests__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Routed for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Spend in Progress</fullName>
            </value>
            <value>
                <fullName>Closure in Process</fullName>
            </value>
            <value>
                <fullName>Closure Approval</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Item__c/Expense_Item__c.object-meta.xml
<CustomObject>
    <description>CFR Database - to store Investment details</description>
    <label>Expense Item</label>
    <nameField>
        <displayFormat>EI-{00000000}</displayFormat>
        <label>Expense Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/fields/Capital_Request__c.field-meta.xml
<CustomField>
    <fullName>Capital_Request__c</fullName>
    <label>Capital Request</label>
    <referenceTo>Capital_Requests__c</referenceTo>
    <relationshipLabel>Expense Items</relationshipLabel>
    <relationshipName>Expense_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Expense_Item__c.field-meta.xml
<CustomField>
    <fullName>Expense_Item__c</fullName>
    <label>Expense Item</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Original__c.field-meta.xml
<CustomField>
    <fullName>Original__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Original</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/HRCCFRSendEmailRemainderHelperTest.cls
@isTest(seeAllData=false)
private class HRCCFRSendEmailRemainderHelperTest{
    static List<Capital_Requests__c> crInitList;
    static User userObj;
    static void initData(){
        Profile p = [SELECT Id FROM Profile WHERE Name='HRC CFR Project Manager']; 
        userObj = new User(Alias = 'standt', Email='financialreviewertest@example.com', 
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p.Id, 
                           TimeZoneSidKey='America/Los_Angeles', UserName='financialreviewer@testorg.com');
        
        insert userObj;
        
        List<RecordType> r = [select id from RecordType where SobjectType = 'Capital_Requests__c' and name='CFR Capital' limit 1];
        
        crInitList = new List<Capital_Requests__c>();
        
        
        for(integer i=0; i<5; i++){
            Capital_Requests__c crObj = new Capital_Requests__c();
            crObj.Status__c = 'Draft';
            crObj.Key_Assumptions__c = 'test';
            crObj.Project_Name__c = 'test name';  
            crObj.RecordTypeId = r[0].id;
            crObj.Financial_Analyst__c = userObj.id;
            crObj.Rejection_Comments_Required__c = 'Test';//Added Sindhu
            crInitList.add(crObj);
        }
        //Inserting list by user object
        System.runAs(userObj){
            insert crInitList;
        }
        
        
        List<Expense_Item__c> EIList = new List<Expense_Item__c>();
        for(Capital_Requests__c cr:crInitList){
            Expense_Item__c expenseItem =  new Expense_Item__c();
            expenseItem.Original__c = 50000;
            //expenseItem.CurrencyIsoCode = 'USD - U.S. Dollar';
            expenseItem.Expense_Item__c = 'Expense Item';
            expenseItem.Capital_Request__c = cr.id;
            EIList.add(expenseItem);
        }
        //Inserting list by user object
        System.runAs(userObj){
            insert EIList;
        }
    }
    
    static void RejectSubmittedRequest(Approval.ProcessResult Result)
    {
        List<Id> newWorkItemIds = result.getNewWorkitemIds();
        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        req.setComments('Rejected');
        req.setAction('Reject');
        req.setWorkitemId(newWorkItemIds[0]);
        // Submit the request for approval
        Approval.ProcessResult result2 =  Approval.process(req);
        
    }
    
    static testMethod void remEmailHelperTriggerTest() {
        
        initData();
        Test.startTest();
        List<Approval.ProcessResult> resultList = new List<Approval.ProcessResult>();
        for(Capital_Requests__c crObj: crInitList) {
            Approval.ProcessSubmitRequest crObjRequest = new Approval.ProcessSubmitRequest(); 
            crObjRequest.setObjectId(crObj.ID);  
            Approval.ProcessResult Result = Approval.Process(crObjRequest);
            resultList.add(Result);
            System.assert(Result.isSuccess());
            System.assertEquals('Pending', Result.getInstanceStatus(),'Instance Status : '+Result.getInstanceStatus());
        }
        
        System.runAs(userObj){
            for(Approval.ProcessResult r:resultList){
                RejectSubmittedRequest(r);
            }
        }
        
        Test.stopTest();
    }
}