force-app/main/default/objects/JDE_Prop__c/JDE_Prop__c.object-meta.xml
<CustomObject>
    <label>JDE Prop</label>
    <nameField>
        <label>Proposal Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JDE Props</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JDE_Prop__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>JDE Props (Ship To)</relationshipLabel>
    <relationshipName>Ship_To_Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ship To)</relationshipLabel>
    <relationshipName>Orders_Ship_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateOpportunityControllerTest.cls
@isTest
public with sharing class CreateOpportunityControllerTest {

	public static testMethod void test() {
	    Account acc=new Account(Name='Test',BillingCountry='United States');
        insert acc;
         
         Order__c ord = new Order__C();
         ord.name='12345678';
         ord.Account__c =acc.id;
         insert ord;
 

       JDE_Prop__c pro = new JDE_Prop__C();
       pro.name='12345678';
       pro.Ship_To__c =acc.id;
       insert pro;
       CreateOpportunityController.getJDEprop(pro.id);
       CreateOpportunityController.getOrder(ord.id);
       CreateOpportunityController.getrecordtypeid('test');
    }

}