force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>ORLI-{0}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.HRCFSL_JDE_CostCenter__c</field>
            <operation>equals</operation>
            <value>99635</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HRCSVC21_OLI_Handler.cls
/*********************************************************************************************************************************************
* Class Name: HRCSVC21_OLI_Handler
* Author: Capgemini
* Date: Nov/21/2021
*******************************************************************************************************************/
global class HRCSVC21_OLI_Handler {
  
    @InvocableVariable(required=true)
    global List<Id> recordIds;
    
    public void onAfterInsert(List<Order_Line_Item__c> NewOrderLineItemList,Map<id,Order_Line_Item__c> oldOrderLineItemMap){
        Id recordTypeId = Schema.SObjectType.Order_Line_Item__c.getRecordTypeInfosByName().get('Parts Order Line Item').getRecordTypeId();
        Set<id> allOLIId= new Set<id>();
        for( Order_Line_Item__c olc: NewOrderLineItemList){
            if(olc.recordTypeId==recordTypeId){
            if(olc.Product__c!=null){
                 allOLIId.add(olc.id);
            }
            }
        }if(!allOLIId.isEmpty()){
            if(!system.isFuture()){
             getPricingitem(allOLIId) ;
            }   
        } 
    }
    public void onAfterUpdate(List<Order_Line_Item__c> NewOrderLineItemList, Map<id,Order_Line_Item__c> oldOrderLineItemMap){ 
        Id recordTypeId = Schema.SObjectType.Order_Line_Item__c.getRecordTypeInfosByName().get('Parts Order Line Item').getRecordTypeId();
        Set<id> allOLIId= new Set<id>();
        for( Order_Line_Item__c olc: NewOrderLineItemList){
            if(olc.RecordTypeId==recordTypeId){
                if(olc.Product__c!=oldOrderLineItemMap.get(olc.id).Product__c){
                //oliList.add(olc);
                allOLIId.add(olc.id);
                }
            }
        } if(!allOLIId.isEmpty()){
             if(!system.isFuture()){
             getPricingitem(allOLIId) ;
             }
        }
    }
     @future(callout=true)
    public static void getPricingitem(set<id> oliId){
        List<Order_Line_Item__c> updateOLIList=new List<Order_Line_Item__c>();
        for(id recordId:oliId){
        Order_Line_Item__c oli = new Order_Line_Item__c ();
            oli=HRCSVC21_Get_Pricing.requestPricingitem(recordId,false);
            if(oli!=null){
                updateOLIList.add(oli);
            }
            system.debug('updateOLIList>>>'+updateOLIList);
        } if(!updateOLIList.isEmpty()){
            database.update(updateOLIList);
        }
    }
    @InvocableMethod(label='Get OLI IDs' description='Returns the list of OLI' category='Order_Line_Item__c')
    public static List<String> getPricing(List<List<String>>oliId) {
         List<String> message=new List<String>();
        try{
        List<String> ids =oliId[0];
        system.debug('Size of id????'+ids.size());
            
        String strLimitOnOLIsToSelect = Label.HRCSVC21_Max_Order_Line_Count_for_selection;
        Integer iLimit = strLimitOnOLIsToSelect == '' ? 50 : Integer.valueOf(strLimitOnOLIsToSelect);
            
        if(ids.size()==1){
              message.add('Please select at least one record');
        }
       else if(ids.size()> iLimit){
              message.add('Please select 50 or less records!');
       }
        else{
              message.add(HRCSVC21_Get_Pricing.passingIds(ids));
            system.debug('???????&&&&&');
        }
        }catch(Exception e){
           
           system.debug('e '+e.getStackTraceString());
             message.add('error???');
                   
        }
       
        return message;
    }    
}