force-app/main/default/objects/Asset/fields/HRCFSL_Next_PM_DT__c.field-meta.xml
<CustomField>
    <fullName>HRCFSL_Next_PM_DT__c</fullName>
    <description>PM Due Date Field</description>
    <label>Next PM Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HRCFSL_ModList__c/HRCFSL_ModList__c.object-meta.xml
<CustomObject>
    <label>Field Action/Mod</label>
    <nameField>
        <label>Field Action/Mod</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Action/Mods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaintenancePlan/fields/HRCFSL_ModList__c.field-meta.xml
<CustomField>
    <fullName>HRCFSL_ModList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Action/Mod</label>
    <referenceTo>HRCFSL_ModList__c</referenceTo>
    <relationshipLabel>Maintenance Plans</relationshipLabel>
    <relationshipName>Maintenance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/HRCFSL_ModList__c.field-meta.xml
<CustomField>
    <fullName>HRCFSL_ModList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Action/Mod</label>
    <referenceTo>HRCFSL_ModList__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/HRCFSL_Work_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>HRCFSL_Work_Type_Name__c</fullName>
    <description>for storing the related work type Name.</description>
    <formula>TEXT( WorkType.HRCFSL_Doc_Type__c ) + TEXT( WorkType.HRCFSL_Activity_Type__c )</formula>
    <label>Work Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HRCSVC_getAssetDetails.cls
/********************
Created on             06-Jan-20211
Created By             Kushagra Bansal - Capgemini 
@description           Class for getting WorkOrder records to correctiveActionMODPM Lightning web component
********************/
public with sharing class HRCSVC_getAssetDetails {
    @AuraEnabled (cacheable=true)
    public static List<WorkOrder> retrieveWorkOrders(){
        return [SELECT Id,WorkOrderNumber,HRCFSL_Work_Type_Name__c,Description,HRCFSL_Next_PM_DT__c,
        HRCFSL_Asset_Product_Description__c,MaintenancePlan.Id, MaintenancePlan.Frequency,MaintenancePlan.FrequencyType, 
        MaintenancePlan.MaintenancePlanNumber, MaintenancePlan.ServiceContractId ,
         ServiceContractId , ServiceContract.Name ,
         AssetId, Asset.Name,
         HRCFSL_Location_Name__c  , Location.HRCFSL_Description__c,
         ServiceTerritoryId, ServiceTerritory.Name,
         EndDate,
         Account.Name,MaintenancePlan.WorkType.Name,
         HRCFSL_ModList__r.Name,HRCFSL_ModList__c
        FROM WorkOrder 
        WHERE  MaintenancePlan.Id!=null
        ORDER BY HRCFSL_Next_PM_DT__c ASC];
    }

       
}