force-app/main/default/objects/Account_Team_Role__c/Account_Team_Role__c.object-meta.xml
<CustomObject>
    <label>Account Team Role</label>
    <nameField>
        <displayFormat>ATR-{00000}</displayFormat>
        <label>Account Team Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team_Role__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Roles</relationshipLabel>
    <relationshipName>Account_Team_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Team_Role__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>ACD</fullName>
            </value>
            <value>
                <fullName>ITSE</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team_Role__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Team_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Record_Type_Position_Map__c/Opportunity_Record_Type_Position_Map__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Maps Opportunity Record Types to User Positions</description>
    <label>Opportunity Record Type Position Map</label>
</CustomObject>

force-app/main/default/objects/Opportunity_Record_Type_Position_Map__c/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Comma-delimited list of Positions related to the &quot;Name&quot; field which will be populated with the Opportunity Record Type name.</description>
    <label>Positions</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchAlignOpportunityOwner1Test.cls
@istest
public class BatchAlignOpportunityOwner1Test {

    //Test Method
    //
    
    static  testmethod void testThisClass() {
        
        
        //create the data for the test
        Account testAccount = new Account(name='test account34');
        insert testAccount;
        if(testAccount.id !=Null){
        
        Account_Team_Role__c atr = new Account_Team_Role__c(AccountId__c = testAccount.id
                                                           ,UserId__c = UserInfo.getUserId()
                                                           ,Position__c = 'test-x',CurrencyIsoCode ='USD');
        insert atr;
        
        
        Opportunity testOpp = new Opportunity(AccountId=testAccount.id, Name='Test Opportunity234343');
        testOpp.Return_Type__c = 'None';
        testOpp.StageName = 'Qualified Opportunity';
        testOpp.CloseDate = system.today();
        testOpp.RMA_Date_1__c = system.today();
        testOpp.RMA_Price_1__c = 100.00 ;
        testOpp.RMA_Product_1__c = 'test product' ;
        testOpp.RMA_Quantity_1__c = 10 ;
        testOpp.ReAssign_Owner__c=true;
        insert testOpp;
        
        //retrieve the default record type
        testOpp = [select Id, RecordType.Name from Opportunity where id = :testOpp.Id];
        
        //add the custom setting record
        Opportunity_Record_Type_Position_Map__c orp = new Opportunity_Record_Type_Position_Map__c(name = testOpp.RecordType.Name
                                                                                                ,positions__c = 'test-x,test-y,test-z');
         
       insert orp;
                
        //Run the batch job
        Test.startTest();
        
        BatchAlignOpportunityOwner1 b = new BatchAlignOpportunityOwner1();
        database.executebatch(b,200);
        
        Test.stopTest();
        
        //verify that the opportunity owner is set appropriatly
        System.AssertEquals(UserInfo.getUserId(), [Select OwnerId from Opportunity where id = :testOpp.Id].OwnerId);
     }
     }
    
    
 
    static  testmethod void testThisClassForElse() {
        //create the data for the test
      
        List<Account> acct = new List<Account>{new Account(name='test account 18'),new Account(name='test account 2')};
        //Account testAccount = new Account(name='test account 1');
        insert acct;
        
        if(acct!=null && !acct.isEmpty()){
        User userRec = new User(LastName='Pissani',Username='alice.pissani@hillrom.com',Email='alice.pissani@hillrom.com',Alias='APissani',TimeZoneSidKey= 'America/Los_Angeles'
                               ,LocaleSidKey='en_US',EmailEncodingKey='UTF-8',ProfileId='00eE0000000lrRK',LanguageLocaleKey='en_US',isActive=true);
        insert userRec;
        
        Account_Team_Role__c atr = new Account_Team_Role__c(AccountId__c = acct[0].id
                                                           ,UserId__c = userRec.Id
                                                           ,Position__c = 'test-a', CurrencyIsoCode ='USD');
        insert atr;
        
        //system.debug('Account_Team_Role__c==>>'+atr.Id+','+atr.AccountId__c+','+atr.AccountId__r.Name);
        Opportunity testOpp = new Opportunity(AccountId=acct[0].id, Name='Test Opportunity234343');
        testOpp.Return_Type__c = 'None';
        testOpp.StageName = 'Qualified Opportunity';
        testOpp.CloseDate = system.today();
        testOpp.RMA_Date_1__c = system.today();
        testOpp.RMA_Price_1__c = 100.00 ;
        testOpp.RMA_Product_1__c = 'test product' ;
        testOpp.RMA_Quantity_1__c = 10 ;
            testOpp.ReAssign_Owner__c=true;
       // testOpp.RecordTypeId = 'a0DE0000002sGXW';
        insert testOpp;
        
        //retrieve the default record type
        testOpp = [select Id, RecordType.Name from Opportunity where id = :testOpp.Id];
        
        //add the custom setting record
        Opportunity_Record_Type_Position_Map__c orp = new Opportunity_Record_Type_Position_Map__c(name = testOpp.RecordType.Name
                                                                                                ,positions__c = 'test-a,test-y,test-z');
       insert orp;
         
        //Run the batch job
        Test.startTest();
        
        BatchAlignOpportunityOwner1 b = new BatchAlignOpportunityOwner1();
        database.executebatch(b,200);
        
        Test.stopTest();
        }
    }
}