force-app/main/default/objects/Account_Team_Role__c/Account_Team_Role__c.object-meta.xml
<CustomObject>
    <label>Account Team Role</label>
    <nameField>
        <displayFormat>ATR-{00000}</displayFormat>
        <label>Account Team Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team_Role__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Roles</relationshipLabel>
    <relationshipName>Account_Team_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Team_Role__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>ACD</fullName>
            </value>
            <value>
                <fullName>ITSE</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team_Role__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Team_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HRCSVC21_Quote_PDF_Extension.cls
public class HRCSVC21_Quote_PDF_Extension {
public List<Account_Team_Role__c> ListofAccountTeamRole{get;set;}
public HRCSVC21_Quote_PDF_Extension(ApexPages.standardController sc)
{
        system.debug('Quote Id ---> '+(id)sc.getRecord().id);
        Id quoteid= (id)sc.getRecord().id;
        Id AccId = [select id,accountid,opportunityid from quote where id=:quoteid][0].AccountId;
    	system.debug('ACCID '+AccId);
		for(Account a  : [SELECT id,(SELECT UserId__r.Name,UserId__r.MobilePhone,UserId__r.Email, Position__c FROM Account_Team_Roles__r  WHERE Position__c = 'CCE'  ORDER BY CreatedDate ASC LIMIT 1) FROM Account WHERE Id = :AccId])
        {
        system.debug('INSIDE ACCOUNT');      
        ListofAccountTeamRole = new List<Account_Team_Role__c>();
            if (!a.Account_Team_Roles__r.isEmpty()){
                ListofAccountTeamRole.add(a.Account_Team_Roles__r);
      	        system.debug('ListofAccountTeamRole -> '+ListofAccountTeamRole[0].UserId__r.Name);    
            }
               
        }     
}    
}