force-app/main/default/objects/Account_Team_Role__c/Account_Team_Role__c.object-meta.xml
<CustomObject>
    <label>Account Team Role</label>
    <nameField>
        <displayFormat>ATR-{00000}</displayFormat>
        <label>Account Team Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team_Role__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Roles</relationshipLabel>
    <relationshipName>Account_Team_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Team_Role__c/fields/JDE_External_Id__c.field-meta.xml
<CustomField>
    <fullName>JDE_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>JDE External Id</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Team_Role__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>ACD</fullName>
            </value>
            <value>
                <fullName>ITSE</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team_Role__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Team_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Department_UK__c.field-meta.xml
<CustomField>
    <fullName>Department_UK__c</fullName>
    <description>Department&apos;s for UK Facilities</description>
    <inlineHelpText>Department&apos;s for UK Facilities</inlineHelpText>
    <label>Department (UK)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Critical Care</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Manual Handling</fullName>
            </value>
            <value>
                <fullName>Maternity</fullName>
            </value>
            <value>
                <fullName>Med/Surg</fullName>
            </value>
            <value>
                <fullName>Occupational Therapy</fullName>
            </value>
            <value>
                <fullName>Physiotherapy</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Tissue Viability</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Facility Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Biomed</fullName>
            </value>
            <value>
                <fullName>Capital SWO Recipient</fullName>
            </value>
            <value>
                <fullName>Clinical</fullName>
            </value>
            <value>
                <fullName>Facilities/Engineering</fullName>
            </value>
            <value>
                <fullName>Facility Leadership</fullName>
            </value>
            <value>
                <fullName>Interim</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Materials Management</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>Operating Room Manager</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Physician</fullName>
            </value>
            <value>
                <fullName>Physician Assistant</fullName>
            </value>
            <value>
                <fullName>Purchasing</fullName>
            </value>
            <value>
                <fullName>Rental SWO Recipient</fullName>
            </value>
            <value>
                <fullName>Respiratory Therapist</fullName>
            </value>
            <value>
                <fullName>Risk Management</fullName>
            </value>
            <value>
                <fullName>Service Contracts SWO Recipient</fullName>
            </value>
            <value>
                <fullName>Wound Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Record_Type_Position_Map__c/Opportunity_Record_Type_Position_Map__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Maps Opportunity Record Types to User Positions</description>
    <label>Opportunity Record Type Position Map</label>
</CustomObject>

force-app/main/default/objects/Opportunity_Record_Type_Position_Map__c/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Comma-delimited list of Positions related to the &quot;Name&quot; field which will be populated with the Opportunity Record Type name.</description>
    <label>Positions</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchAlignOpportunityOwnerTest.cls
/*
 *  ClassName    : BatchAlignOpportunityOwnerTest
 *  CreatedOn    : 31/Oct/2017
 *  ModifiedOn   : 31/Oct/2017
 *  CreatedBy    : Jenish Shingala
 *  ModifiedBy   : Jenish Shingala
 *  Description  : Test class for BatchAlignOpportunityOwner Batch Class.
 */
@isTest
public with sharing class BatchAlignOpportunityOwnerTest{

    public static testMethod void test() {
        //Insert an Account.
        Account objAccount= new Account();
        objAccount.name = 'Test Account';
        objAccount.BillingCity = 'Pune';
        objAccount.BillingCountry = 'India';
        objAccount.BillingPostalCode = '411033';
       // objAccount.LIKO_Level_2_Emp_Num__c = 'test44';
        // objAccount.LIKO_Level_3_Emp_Num__c = 'test33';
        
        insert objAccount;
        
        //Insert a Contact.
        Contact objContact = new Contact();
        objContact.FirstName = 'test first name';
        objContact.lastname = 'test last name';
        objContact.accountid = objAccount.id;
        objContact.Email = 'testname@apttus.com';
        objContact.Department_UK__c = 'Finance';
        objContact.Role__c = 'Administrator';
        insert objContact;
        
        string opprecordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('CWS').getRecordTypeId();
        
        //Insert Opportunity.
        Opportunity objOpp = new Opportunity();
        objOpp.accountid = objAccount.id;
        objOpp.name = 'Test name';
        objOpp.StageName = 'Developing Opportunity';
        objOpp.CloseDate = Date.today().adddays(1);
        objOpp.Project_Type_Rental__c = 'Asset Advantage';
        objOpp.Order_Contact__c = objContact.id;
        objOpp.recordtypeid = opprecordtypeid;
        insert objOpp;
        
        //Insert Custom setting.
        
        Opportunity_Record_Type_Position_Map__c objMapTest = new Opportunity_Record_Type_Position_Map__c();
        objMapTest.Name = 'HITS';
        objMapTest.Positions__c = 'ITSE,CN-WFPM,AM,CM,ACM,ESSS01,ESSS02';
        insert objMapTest;
        
        //Insert User.
        Profile p = [SELECT Id FROM Profile WHERE Name='HRC CFR Project Manager']; 
        User userObj  = new User(Alias = 'standt', Email='financialreviewertest@example.com', 
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p.Id, 
                           TimeZoneSidKey='America/Los_Angeles', UserName='financialreviewer@testorg.com',jde_external_id__c = 'test33');
        
        insert userObj;
        
        //Insert Account Team Role.
        Account_Team_Role__c objAccountTeamRole = new Account_Team_Role__c();
        objAccountTeamRole.AccountId__c = objAccount.id;
        objAccountTeamRole.UserId__c = userObj.id;
        objAccountTeamRole.Position__c = 'ITSE';
        insert objAccountTeamRole;
        
        Test.StartTest();
        BatchAlignOpportunityOwner objCls = new BatchAlignOpportunityOwner();
        ID batchprocessid = Database.executeBatch(objCls);
        Test.StopTest();
        
        system.assertEquals('ITSE',objAccountTeamRole.Position__c);


    }

}