force-app/main/default/objects/PLD_Record_Type__mdt/PLD_Record_Type__mdt.object-meta.xml
<CustomObject>
    <description>Manages which record types can be processed by the Purposeful Lead Duplication process.</description>
    <label>PLD Record Type</label>
    <pluralLabel>PLD Record Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/PLD_Record_Type__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, the record type will be processed.</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PLD_Synced_Field__mdt/PLD_Synced_Field__mdt.object-meta.xml
<CustomObject>
    <description>Fields that are to be synced between the Parent and Child leads during the Purposeful Lead Duplication process.</description>
    <label>PLD Synced Field</label>
    <pluralLabel>PLD Synced Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/PLD_Synced_Field__mdt/fields/ChildFieldName__c.field-meta.xml
<CustomField>
    <fullName>ChildFieldName__c</fullName>
    <description>API Name of the field on the child Lead to be synced.</description>
    <label>Child Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLD_Synced_Field__mdt/fields/MergedTextFieldSeparator__c.field-meta.xml
<CustomField>
    <fullName>MergedTextFieldSeparator__c</fullName>
    <defaultValue>&apos;;&apos;</defaultValue>
    <label>Merged Text Field Separator</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLD_Synced_Field__mdt/fields/MergePicklist__c.field-meta.xml
<CustomField>
    <fullName>MergePicklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Merges a single picklist with a multi-picklist.</description>
    <label>Merge Picklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PLD_Synced_Field__mdt/fields/MergeTextField__c.field-meta.xml
<CustomField>
    <fullName>MergeTextField__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Merge Text Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PLD_Synced_Field__mdt/fields/ParentFieldName__c.field-meta.xml
<CustomField>
    <fullName>ParentFieldName__c</fullName>
    <description>API Name of the field on the Parent Object</description>
    <label>Parent Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLD_Synced_Field__mdt/fields/SyncCondition__c.field-meta.xml
<CustomField>
    <fullName>SyncCondition__c</fullName>
    <defaultValue>&apos;Always&apos;</defaultValue>
    <description>Determines when the sync should occur.</description>
    <inlineHelpText>Always indicates the field should be synced, even when no changes in the field occur; When Changed will only sync when the field value has changed; Only on creation will only sync when the child is first created.</inlineHelpText>
    <label>Sync Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Always</fullName>
                <default>true</default>
                <label>Always</label>
            </value>
            <value>
                <fullName>When changed</fullName>
            </value>
            <value>
                <fullName>Only on creation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PLD_Synced_Field__mdt/fields/SyncDirection__c.field-meta.xml
<CustomField>
    <fullName>SyncDirection__c</fullName>
    <description>Controls the direction of the sync.</description>
    <label>Sync Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bidirectional</fullName>
                <default>true</default>
                <label>Bidirectional</label>
            </value>
            <value>
                <fullName>To Parent</fullName>
            </value>
            <value>
                <fullName>To Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Constants.cls
/* Class:       Constants
** Created by:  OpFocus (Jason Curry) on 2021-06-21
** Description: System constants file
*/

public class Constants {

    @TestVisible
    private Constants() { /* Singleton */}

    // Lead Constants

    public static final String PARDOT_USERNAME = 'pardot@system.id.%';

    public static User PARDOT_USER {
        get {
            if (PARDOT_USER == null) {
                PARDOT_USER = [SELECT Id, Username, Name FROM User WHERE Username LIKE :PARDOT_USERNAME LIMIT 1];
            }
            return PARDOT_USER;
        }
        set;
    }

    public static final String LEAD_PLD_LEAD_TYPE_PARENT = 'Parent Lead';
    public static final String LEAD_PLD_LEAD_TYPE_CHILD = 'Child Lead';

    public static final Map<Id, RecordTypeInfo> LEAD_RECORD_TYPES_BY_ID {
        get {
            if (LEAD_RECORD_TYPES_BY_ID == null) {
                LEAD_RECORD_TYPES_BY_ID = Schema.Lead.getSObjectType().getDescribe().getRecordTypeInfosById();
            }
            return LEAD_RECORD_TYPES_BY_ID;
        }
        private set;
    }

    public static final Map<String, RecordTypeInfo> LEAD_RECORD_TYPES_BY_DEVELOPER_NAME {
        get {
            if (LEAD_RECORD_TYPES_BY_DEVELOPER_NAME == null) {
                LEAD_RECORD_TYPES_BY_DEVELOPER_NAME = Schema.Lead.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName();
            }
            return LEAD_RECORD_TYPES_BY_DEVELOPER_NAME;
        }
        private set;
    }

    // PLD Constants
    public static final Map<String, PLD_Record_Type__mdt> PLD_RECORD_TYPES {
        get {
            if (PLD_RECORD_TYPES == null) {
                List<PLD_Record_Type__mdt> recordTypes = [SELECT DeveloperName
                FROM PLD_Record_Type__mdt WHERE Enabled__c = TRUE ORDER BY DeveloperName DESC];

                PLD_RECORD_TYPES = new Map<String, PLD_Record_Type__mdt>();
                for (PLD_Record_Type__mdt rt : recordTypes) {
                    PLD_RECORD_TYPES.put(rt.DeveloperName, rt);
                }
            }
            return PLD_RECORD_TYPES;
        }
        private set;
    }

    public static Map<String, PLD_Synced_Field__mdt> PLD_SYNCED_FIELDS {
        get {
            if (PLD_SYNCED_FIELDS == null) {
                List<PLD_Synced_Field__mdt> syncedFields = [
                        SELECT
                                Label,
                                DeveloperName,
                                ParentFieldName__c,
                                ChildFieldName__c,
                                SyncDirection__c,
                                SyncCondition__c,
                                MergePicklist__c,
                                MergeTextField__c,
                                MergedTextFieldSeparator__c
                        FROM PLD_Synced_Field__mdt
                ];

                PLD_SYNCED_FIELDS = new Map<String, PLD_Synced_Field__mdt>();
                for (PLD_Synced_Field__mdt f : syncedFields) {
                    PLD_SYNCED_FIELDS.put(f.DeveloperName, f);
                }
            }
            return PLD_SYNCED_FIELDS;
        }
        private set;
    }

    public static final String PLD_DIRECTION_BIDIRECTIONAL = 'Bidirectional';
    public static final String PLD_DIRECTION_TO_PARENT = 'To Parent';
    public static final String PLD_DIRECTION_TO_CHILD = 'To Child';

    public static final String PLD_CONDITION_ALWAYS = 'Always';
    public static final String PLD_CONDITION_WHEN_CHANGED = 'When changed';
    public static final String PLD_CONDITION_ONLY_ON_CREATION = 'Only on creation';

}