force-app/main/default/objects/HRCSVC20_CQ_Original_Values__c/HRCSVC20_CQ_Original_Values__c.object-meta.xml
<CustomObject>
    <description>SE-2620 - CQs for Translation, This object is used to review the qualified CQs for translation, so that only translated information can sync over to EtQ</description>
    <label>CQ_Original_Values</label>
    <nameField>
        <label>CQ_Original_Values__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CQ_Original_Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HRCSVC20_CQ_Original_Values__c/fields/HRCSVC20_CQ__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_CQ__c</fullName>
    <description>SE-2620 - Detail to Complaint Qualifications Master Object (Service Cloud 2.1)</description>
    <label>CQ</label>
    <referenceTo>HRCSVC_Complaint_Qualification__c</referenceTo>
    <relationshipLabel>CQ_Original_Values</relationshipLabel>
    <relationshipName>CQ_Original_Values</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HRCSVC20_CQ_Original_Values__c/fields/HRCSVC20_CQ_Key__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_CQ_Key__c</fullName>
    <description>SE-2620 - Key of Field Label whose value needs to be captured for Translation (Service Cloud 2.1)</description>
    <label>CQ_Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC20_CQ_Original_Values__c/fields/HRCSVC20_CQ_Value__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_CQ_Value__c</fullName>
    <description>SE-2620 - Field Value needs to be captured for Translation (Service Cloud 2.1)</description>
    <label>CQ_Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC_Complaint_Qualification__c/HRCSVC_Complaint_Qualification__c.object-meta.xml
<CustomObject>
    <label>Complaint Qualification</label>
    <nameField>
        <displayFormat>CQ-{0000}</displayFormat>
        <label>Complaint Qualification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HRCSVC_Complaint_Qualification__c/fields/HRCSVC20_Requires_Translation__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_Requires_Translation__c</fullName>
    <defaultValue>true</defaultValue>
    <description>SE-2620:I want to review the qualified CQs for translation so that I can ensure only translated information can sync over to EtQ (Service Cloud 2.1) - By default checked and gets unchecked with Send To ETQ action. Used In a report (CQ&apos;s that Require Translation) which filters records based on Case and WO language.</description>
    <label>Requires Translation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HRCSVC20_CQ_Backup_Values.cls
/***********************************************************************************************************************************************
* Name                             :  HRCSVC20_CQ_Backup_Values
* Author                           :  Capgemini
* Date                             :  November'21
* Requirement/Project Name         :  Hill-Rom
* Requirement/Project Description  :  SE-2620
/***********************************************************************************************************************************************/
global class HRCSVC20_CQ_Backup_Values
{
public static Id RecordId;
public static boolean isSuccess;
public static String SobjectName;
public static String FsetName; 
public static List<String> Allfields;
public static map<string,String> AllfieldLabels;    
public static List<HRCSVC20_CQ_Original_Values__c> CQOriginalValues;    
public static Map<String,String> KeyValuepairs;
public static Schema.FieldSet Fset;

global class BackupCQValues
{ 
    
@InvocableVariable(required=true)
global Id recId;
    
@InvocableVariable(required=true)
global String fldsetname;

}

global class returnmessage
{ 
@InvocableVariable
global String succerrmsg;
}

    
@InvocableMethod(label='Update CQ Original Values' description='Update CQ Original Values' category='Account')
public static list<returnmessage> HRCSVC20_CQ_Backup_Values(List<BackupCQValues> InputValues)    

{    
returnmessage returnresults = new returnmessage();    
list<returnmessage> succerrmessage = new list<returnmessage>();
try
{
RecordId = InputValues[0].recId;
FsetName =  InputValues[0].fldsetname;
       
Schema.FieldSet Fset;
KeyValuepairs = new Map<String,String>();
CQOriginalValues = new List<HRCSVC20_CQ_Original_Values__c>();      
SobjectName = RecordId.getSObjectType().getDescribe().getName();
Allfields = new List<String>();
AllfieldLabels = new map<string,String>();
Fset = HRCSVC_Complaint_Qualification__c.sObjectType.getDescribe().fieldSets.getMap().get(FsetName);

HRCSVC_Complaint_Qualification__c a = (HRCSVC_Complaint_Qualification__c) HRCSVC20_Dynamic_Fetch_Field_Values.fetchSobjectValues(RecordId, FsetName,Fset);

AllfieldLabels = HRCSVC20_Dynamic_Fetch_Field_Values.ReturnFieldsetLabels();
for(String s : HRCSVC20_Dynamic_Fetch_Field_Values.ReturnFieldsetFields(FsetName,fset))
{    
HRCSVC20_CQ_Original_Values__c cqorgrec = new HRCSVC20_CQ_Original_Values__c();
if(!String.isblank((String)a.get(s)))
{    
cqorgrec.HRCSVC20_CQ__c= a.id;   
cqorgrec.HRCSVC20_CQ_Key__c= AllfieldLabels.get(s);
system.debug('AllfieldLabels.get(s) ==>'+AllfieldLabels.get(s));    
cqorgrec.HRCSVC20_CQ_Value__c=(string)a.get(s);
CQOriginalValues.add(cqorgrec);
KeyValuepairs.put(s,(string)a.get(s));
}
}
   
   //delete existing cq backup values
   if(recordid != null)
   {
   list<HRCSVC20_CQ_Original_Values__c> deletion = new list<HRCSVC20_CQ_Original_Values__c>([select id from HRCSVC20_CQ_Original_Values__c where HRCSVC20_CQ__c = :recordid]);
   system.debug('deletion ==> '+deletion);
   Delete deletion;
   }
    
   //insert new cq backup values
   Insert CQOriginalValues;
   a.HRCSVC20_Requires_Translation__c = true;
   update a;
   returnresults = new returnmessage();
   returnresults.succerrmsg = System.label.HRCSVC20_CQ_backup_success_message;
   succerrmessage.add(returnresults);

    }   
   catch(exception e)
   {
   returnresults = new returnmessage();
   returnresults.succerrmsg = System.label.HRCSVC20_CQ_backup_error_message;
   succerrmessage.add(returnresults);
   system.debug('e '+e.getMessage());    
   }

  return succerrmessage; 

}
}