force-app/main/default/objects/HRCSVC20_CQ_Original_Values__c/HRCSVC20_CQ_Original_Values__c.object-meta.xml
<CustomObject>
    <description>SE-2620 - CQs for Translation, This object is used to review the qualified CQs for translation, so that only translated information can sync over to EtQ</description>
    <label>CQ_Original_Values</label>
    <nameField>
        <label>CQ_Original_Values__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CQ_Original_Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HRCSVC20_CQ_Original_Values__c/fields/HRCSVC20_CQ__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_CQ__c</fullName>
    <description>SE-2620 - Detail to Complaint Qualifications Master Object (Service Cloud 2.1)</description>
    <label>CQ</label>
    <referenceTo>HRCSVC_Complaint_Qualification__c</referenceTo>
    <relationshipLabel>CQ_Original_Values</relationshipLabel>
    <relationshipName>CQ_Original_Values</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HRCSVC20_CQ_Original_Values__c/fields/HRCSVC20_CQ_API_Name__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_CQ_API_Name__c</fullName>
    <label>CQ API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC20_CQ_Original_Values__c/fields/HRCSVC20_CQ_Key__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_CQ_Key__c</fullName>
    <description>SE-2620 - Key of Field Label whose value needs to be captured for Translation (Service Cloud 2.1)</description>
    <label>CQ_Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC20_CQ_Original_Values__c/fields/HRCSVC20_CQ_Value__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC20_CQ_Value__c</fullName>
    <description>SE-2620 - Field Value needs to be captured for Translation (Service Cloud 2.1)</description>
    <label>CQ_Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC20_CQ_Original_Values__c/fields/HRCSVC21_CQ_Translation__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC21_CQ_Translation__c</fullName>
    <label>CQ Translation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRCSVC_Complaint_Qualification__c/HRCSVC_Complaint_Qualification__c.object-meta.xml
<CustomObject>
    <label>Complaint Qualification</label>
    <nameField>
        <displayFormat>CQ-{0000}</displayFormat>
        <label>Complaint Qualification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HRCSV21_CQ_Original_Values_Handler.cls
/***********************************************************************************************************************************************
* Name                             :  HRCSV21_CQ_Original_Values_Handler
* Author                           :  Capgemini
* Date                             :  November'21
* Purpose                          :  This class handles updates to the Translated values to the corresponding field to the 
									  Parent Complaint Qualification record									  
* Requirement/Project Name         :  Hill-Rom
* Requirement/Project Description  :  SE-2620
/***********************************************************************************************************************************************/

public class HRCSV21_CQ_Original_Values_Handler extends TriggerHandler 
{
public static Schema.FieldSet Fset;

public override void afterupdate()
{
system.debug('HRCSV21_CQ_Original_Values_Handler trigger.newmap '+trigger.newmap.values());    
list<string> fieldapinames = new list<string>();
HRCSVC_Complaint_Qualification__c parentcqrecord; // = new HRCSVC_Complaint_Qualification__c  ();
try{    
        
for (HRCSVC20_CQ_Original_Values__c fldsupdated : [select id,name,HRCSVC20_CQ__c,HRCSVC20_CQ_Key__c,HRCSVC20_CQ_Value__c,HRCSVC20_CQ_API_Name__c,HRCSVC21_CQ_Translation__c from HRCSVC20_CQ_Original_Values__c where id in :trigger.newmap.keyset()])
{
system.debug('PARENT ID '+fldsupdated.HRCSVC20_CQ__c);
Fset = HRCSVC_Complaint_Qualification__c.sObjectType.getDescribe().fieldSets.getMap().get('HRCSVC20_CQ_Translation');
if(parentcqrecord == null)
{
parentcqrecord = new HRCSVC_Complaint_Qualification__c  ();
parentcqrecord = (HRCSVC_Complaint_Qualification__c) HRCSVC20_Dynamic_Fetch_Field_Values.fetchSobjectRecValues(fldsupdated.HRCSVC20_CQ__c,fset);
}
system.debug('parentcqrecord '+parentcqrecord);    
if(!String.isblank(fldsupdated.HRCSVC21_CQ_Translation__c) && (fldsupdated.HRCSVC21_CQ_Translation__c != parentcqrecord.get(fldsupdated.HRCSVC20_CQ_API_Name__c)))
{
system.debug('Field API Name ----> '+fldsupdated.HRCSVC20_CQ_API_Name__c);    
system.debug('Original CQ Field Value ----> '+parentcqrecord.get(fldsupdated.HRCSVC20_CQ_API_Name__c));
parentcqrecord.put(fldsupdated.HRCSVC20_CQ_API_Name__c,fldsupdated.HRCSVC21_CQ_Translation__c);   
system.debug('New Translated Value ------> '+fldsupdated.HRCSVC21_CQ_Translation__c);
system.debug('CQ Backup value -----> '+fldsupdated.HRCSVC20_CQ_Value__c);                
}
}
update parentcqrecord;
}
catch(exception e)
{
 system.debug('Exception in HRCSV21_CQ_Original_Values_Handler --->'+e.getStackTraceString());
}
}

}