force-app/main/default/objects/Contact/fields/Department_UK__c.field-meta.xml
<CustomField>
    <fullName>Department_UK__c</fullName>
    <description>Department&apos;s for UK Facilities</description>
    <inlineHelpText>Department&apos;s for UK Facilities</inlineHelpText>
    <label>Department (UK)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Critical Care</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Manual Handling</fullName>
            </value>
            <value>
                <fullName>Maternity</fullName>
            </value>
            <value>
                <fullName>Med/Surg</fullName>
            </value>
            <value>
                <fullName>Occupational Therapy</fullName>
            </value>
            <value>
                <fullName>Physiotherapy</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Tissue Viability</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Facility Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Biomed</fullName>
            </value>
            <value>
                <fullName>Capital SWO Recipient</fullName>
            </value>
            <value>
                <fullName>Clinical</fullName>
            </value>
            <value>
                <fullName>Facilities/Engineering</fullName>
            </value>
            <value>
                <fullName>Facility Leadership</fullName>
            </value>
            <value>
                <fullName>Interim</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Materials Management</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>Operating Room Manager</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Physician</fullName>
            </value>
            <value>
                <fullName>Physician Assistant</fullName>
            </value>
            <value>
                <fullName>Purchasing</fullName>
            </value>
            <value>
                <fullName>Rental SWO Recipient</fullName>
            </value>
            <value>
                <fullName>Respiratory Therapist</fullName>
            </value>
            <value>
                <fullName>Risk Management</fullName>
            </value>
            <value>
                <fullName>Service Contracts SWO Recipient</fullName>
            </value>
            <value>
                <fullName>Wound Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StrategicDealInfoControllerTest.cls
@isTest
public with sharing class StrategicDealInfoControllerTest{

	public static testMethod void test() {
         //Insert an Account.
        Account objAccount= new Account();
        objAccount.name = 'Test Account';
        objAccount.BillingCity = 'Pune';
        objAccount.BillingCountry = 'India';
        objAccount.BillingPostalCode = '411033';
        insert objAccount;
        
        //Insert a Contact.
        Contact objContact = new Contact();
        objContact.lastname = 'test last name';
        objContact.accountid = objAccount.id;
        objContact.Department_UK__c = 'Finance';
        objContact.Role__c = 'Administrator';
        objContact.Phone = '+918123412345';
        insert objContact;
        
        //Insert Opportunity.
        Opportunity objOpp = new Opportunity();
        objOpp.accountid = objAccount.id;
        objOpp.name = 'Test name';
        objOpp.StageName = 'Developing Opportunity';
        objOpp.CloseDate = Date.today().adddays(1);
        objOpp.Project_Type_Rental__c = 'Asset Advantage';
        objOpp.Order_Contact__c = objContact.id;
        insert objOpp;
        system.assertEquals(objOpp.name,'Test name');
        ApexPages.StandardController con = new ApexPages.StandardController(objOpp);
        ApexPages.currentPage().getParameters().put('id',objOpp.id);
        
        StrategicDealInfoController objCls = new StrategicDealInfoController(con);
        objCls.saveDealReview();
        
        WinLossAnalysisController objCls1 = new WinLossAnalysisController(con);
        objCls1.saveWinLossAnalysis();
          
	}
	
	public static testMethod void test2() {
         //Insert an Account.
        Account objAccount= new Account();
        objAccount.name = 'Test Account';
        objAccount.BillingCity = 'Pune';
        objAccount.BillingCountry = 'India';
        objAccount.BillingPostalCode = '411033';
        insert objAccount;
        
        //Insert a Contact.
        Contact objContact = new Contact();
        objContact.lastname = 'test last name';
        objContact.accountid = objAccount.id;
        objContact.Department_UK__c = 'Finance';
        objContact.Role__c = 'Administrator';
         objContact.Phone = '+918123412345';
        insert objContact;
        
        //Insert Opportunity.
        Opportunity objOpp = new Opportunity();
        objOpp.accountid = objAccount.id;
        objOpp.name = 'Test name';
        objOpp.StageName = 'Developing Opportunity';
        objOpp.CloseDate = Date.today().adddays(1);
        objOpp.Project_Type_Rental__c = 'Asset Advantage';
        objOpp.Order_Contact__c = objContact.id;
        insert objOpp;
        
        system.assertEquals(objOpp.name,'Test name');
        
        ApexPages.StandardController con = new ApexPages.StandardController(objOpp);
        //ApexPages.currentPage().getParameters().put('id',objOpp.id);
        
        StrategicDealInfoController objCls = new StrategicDealInfoController(con);
        objCls.saveDealReview();
        
        WinLossAnalysisController objCls1 = new WinLossAnalysisController(con);
        objCls1.saveWinLossAnalysis();
          
	}

}