force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <description>Replacement for Lotus Notes CEC Trip Planner</description>
    <label>CEC Visit Planner</label>
    <nameField>
        <displayFormat>CEC-{00000}</displayFormat>
        <label>Trip Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEC Visit Planner</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>CEC_Visitation_Planner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Host_Cell_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Host_Cell_Phone_Number__c</fullName>
    <label>Host Cell Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Host_Name_1__c.field-meta.xml
<CustomField>
    <fullName>Host_Name_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CEC_Visitation_Planner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Nearest_Major_Airport_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Nearest_Major_Airport_to_Customer__c</fullName>
    <label>Nearest Major Airport to Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aberdeen,SD-ABR</fullName>
            </value>
            <value>
                <fullName>Abilene,TX-ABI</fullName>
            </value>
            <value>
                <fullName>Adak Island,AK-ADK</fullName>
            </value>
            <value>
                <fullName>Akiachak,AK-KKI</fullName>
            </value>
            <value>
                <fullName>Akiak,AK-AKI</fullName>
            </value>
            <value>
                <fullName>Akron/Canton,OH-CAK</fullName>
            </value>
            <value>
                <fullName>Akuton,AK-KQA</fullName>
            </value>
            <value>
                <fullName>Alakanuk,AK-AUK</fullName>
            </value>
            <value>
                <fullName>Alamogordo,NM-ALM</fullName>
            </value>
            <value>
                <fullName>Alamosa,CO-ALS</fullName>
            </value>
            <value>
                <fullName>Albany,NY-ALB</fullName>
            </value>
            <value>
                <fullName>Albany,OR-CVO</fullName>
            </value>
            <value>
                <fullName>Albany,OR-QWY</fullName>
            </value>
            <value>
                <fullName>Albuquerque,NM-ABQ</fullName>
            </value>
            <value>
                <fullName>Aleknagik,AK-WKK</fullName>
            </value>
            <value>
                <fullName>Alexandria,LA-AEX</fullName>
            </value>
            <value>
                <fullName>Allakaket,AK-AET</fullName>
            </value>
            <value>
                <fullName>Allentown,PA-ABE</fullName>
            </value>
            <value>
                <fullName>Alliance,NE-AIA</fullName>
            </value>
            <value>
                <fullName>Alpena,MI-APN</fullName>
            </value>
            <value>
                <fullName>Altoona,PA-AOO</fullName>
            </value>
            <value>
                <fullName>Amarillo,TX-AMA</fullName>
            </value>
            <value>
                <fullName>Ambler,AK-ABL</fullName>
            </value>
            <value>
                <fullName>Anaktueuk,AK-AKP</fullName>
            </value>
            <value>
                <fullName>Anchorage,AK-ANC</fullName>
            </value>
            <value>
                <fullName>Angoon,AK-AGN</fullName>
            </value>
            <value>
                <fullName>Aniak,AK-ANI</fullName>
            </value>
            <value>
                <fullName>Anvik,AK-ANV</fullName>
            </value>
            <value>
                <fullName>Appleton,WI-ATW</fullName>
            </value>
            <value>
                <fullName>Arcata,CA-ACV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Opportunity for CEC Trip</description>
    <inlineHelpText>Primary Opportunity for CEC Trip</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>CEC_Visitation_Planner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Proposed_Trip_Date__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Trip_Date__c</fullName>
    <description>This Date is only a suggested date. The trip will be Confirmed by your CEC Coordinator.</description>
    <inlineHelpText>This Date is only a suggested date. The trip will be Confirmed by your CEC Coordinator.</inlineHelpText>
    <label>Proposed Trip Date</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Trip_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Trip_End_Date__c</fullName>
    <label>Trip End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Trip_Location__c.field-meta.xml
<CustomField>
    <fullName>Trip_Location__c</fullName>
    <label>Trip Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Batesville</fullName>
            </value>
            <value>
                <fullName>Irvine</fullName>
            </value>
            <value>
                <fullName>Cary</fullName>
            </value>
            <value>
                <fullName>Charleston</fullName>
            </value>
            <value>
                <fullName>CWS Site</fullName>
            </value>
            <value>
                <fullName>Mississauga</fullName>
            </value>
            <value>
                <fullName>Pluvigner</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Trip_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Trip_Request_Status__c</fullName>
    <description>Indicates the Current Trip Request Status of the CEC Trip. Default Status is Submitted.</description>
    <inlineHelpText>Trip Request Status can only be updated to Confirmed or Cancelled by a CEC Specialist.</inlineHelpText>
    <label>Trip Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>CLOSED-CEC</fullName>
            </value>
            <value>
                <fullName>CLOSED-JAWACDAH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Trip_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Trip_Start_Date__c</fullName>
    <label>Trip Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Vest__c.field-meta.xml
<CustomField>
    <fullName>Vest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Vest (R)</description>
    <inlineHelpText>Vest (R)</inlineHelpText>
    <label>Respiratory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CECTriggerTest.cls
@isTest ( seealldata = true)
private class CECTriggerTest {

    static testMethod void runPositiveTestCases() {
       
        
        //Set up user
         User u1 = [SELECT Id FROM User WHERE profile.name = 'System Administrator' and isactive = true limit 1];
         contact c1 = [SELECT Id FROM contact limit 1];
        opportunity o1 = [SELECT Id FROM Opportunity order by createddate asc limit 1 ];
        opportunity o2 = [SELECT Id FROM Opportunity order by createddate desc limit 1];
        id rid = [SELECT Id FROM RecordType WHERE Name = 'Opportunity Based Commercial Air'].id;
        //Run As U1
        

            
        System.debug('Inserting 300  miles... (single record validation)');
        
        Trip__c test1a = new Trip__c(recordtypeid = rid,Host_Name_1__c = u1.id, 
                                        Host_Cell_Phone_Number__c = '1234567890',
                                        Proposed_Trip_Date__c = 'May 2012',
                                        Trip_Location__c = 'Irvine',
                                        Trip_Request_Status__c = 'Submitted',
                                        Trip_Start_Date__c = system.today(),
                                        Trip_End_Date__c =  system.today()+5,
                                        Vest__c = true, Opportunity__c = o1.id,
                                        Nearest_Major_Airport_to_Customer__c = 'Aberdeen,SD-ABR',
                                        Customer_Contact__c = c1.id);
        insert test1a;
         Trip__c test2 = new Trip__c (id = test1a.id, Opportunity__c = o1.id);
         update test2;
      
        } 
       }