force-app/main/default/objects/HRCSVC_Complaint_Qualification__c/HRCSVC_Complaint_Qualification__c.object-meta.xml
<CustomObject>
    <label>Complaint Qualification</label>
    <nameField>
        <displayFormat>CQ-{0000}</displayFormat>
        <label>Complaint Qualification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HRCSVC_Complaint_Qualification__c/fields/HRCSVC_Aware_Date__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC_Aware_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>SE-163 - Default to Current Date</description>
    <label>Aware Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HRCSVC_Complaint_Qualification__c/fields/HRCSVC_Injury_or_Death__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC_Injury_or_Death__c</fullName>
    <description>SE-163 - Complaint Determination- Priority 1- If = Injury or Death regardless of other values on the form= Complaint</description>
    <label>Injury or Death</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blank</fullName>
                <default>true</default>
                <label>Blank</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Injury/Other Patient Involvement</fullName>
            </value>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Asked but not provided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HRCSVC_Complaint_Qualification__c/fields/HRCSVC_Status__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC_Status__c</fullName>
    <description>SE-163 - Value is determined off the Priority Complaint Values</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not a Complaint</fullName>
            </value>
            <value>
                <fullName>Qualified Complaint</fullName>
            </value>
            <value>
                <fullName>Cloned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HRCSVC20_CQ_Backup_Values_Test.cls
/***********************************************************************************************************************************************
* Name                             :  HRCSVC20_CQ_Backup_Values_Test
* Author                           :  Capgemini
* Date                             :  November'21
* Requirement/Project Name         :  Hill-Rom
* Requirement/Project Description  :  SE-2620 test class for HRCSVC20_CQ_Backup_Values and HRCSVC20_Dynamic_Fetch_Field_Values
/***********************************************************************************************************************************************/


@isTest
public class HRCSVC20_CQ_Backup_Values_Test {

    @isTest
    public static void backupValueandDynamicValueTest(){
       HRCSVC20_CQ_Backup_Values baValues= new HRCSVC20_CQ_Backup_Values() ;
        HRCSVC_Complaint_Qualification__c cq= new HRCSVC_Complaint_Qualification__c(HRCSVC_Aware_Date__c=system.today(),HRCSVC_Status__c='Qualified Complaint',HRCSVC_Injury_or_Death__c='Death');
        /*cq.HRCSVC_Aware_Date__c=system.today();
        cq.HRCSVC_Status__c='Qualified Complaint';
        cq.HRCSVC_Injury_or_Death__c='Death';*/
        insert cq;
       List< HRCSVC20_CQ_Backup_Values.BackupCQValues> bcqList= new List<HRCSVC20_CQ_Backup_Values.BackupCQValues>();
            HRCSVC20_CQ_Backup_Values.BackupCQValues bcq= new HRCSVC20_CQ_Backup_Values.BackupCQValues();
        HRCSVC20_CQ_Backup_Values.returnmessage rm = new  HRCSVC20_CQ_Backup_Values.returnmessage();
        rm.succerrmsg='';
           bcq.recId=cq.id;
            bcq.fldsetname='HRCSVC20_CQ_Translation';
           bcqList.add(bcq);
        HRCSVC20_CQ_Backup_Values.HRCSVC20_CQ_Backup_Values(null);
        HRCSVC20_CQ_Backup_Values.HRCSVC20_CQ_Backup_Values(bcqList);
    }
    
    
}