force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/HRCSVC_ERP_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC_ERP_Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>Order Number</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/HRCSVC_Patient_First_Name__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC_Patient_First_Name__c</fullName>
    <label>Patient First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HRCSVC_Patient_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC_Patient_Last_Name__c</fullName>
    <label>Patient Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HRCSVC_Proposal_Date__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC_Proposal_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Order Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HRCSVC_Ship_To_Location__c.field-meta.xml
<CustomField>
    <fullName>HRCSVC_Ship_To_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To (Location)</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Proposal_Date__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Date__c</fullName>
    <label>Order Date *</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>ORLI-{0}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.HRCFSL_JDE_CostCenter__c</field>
            <operation>equals</operation>
            <value>99635</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HRCSVC21_OLI_Handler_Test.cls
/*********************************************************************************************************************************************
* Class Name: HRCSVC21_OLI_Handler_Test
* Author: Capgemini
* Date: Dec/02/2021
***************************************************************************************************************/
@isTest
public class HRCSVC21_OLI_Handler_Test implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
        String fullJson = 'your Json Response';
        HTTPResponse res = new HTTPResponse();
        res.setHeader('Content-Type', 'text/json');
        res.setBody(fullJson);
        res.setStatusCode(200);
        return res;
    }
    @testSetup
    static void setupData() {
        Schema.Location locationNew = HRCFSL_TestUtilityClass.createCustomer(true, 'Customer1234');
       // ServiceTerritory st = HRCFSL_TestUtilityClass.createServiceTerritory(true, 'test12345', 'My Place');
        Product2 product1 = HRCFSL_TestUtilityClass.createProduct(true, 'PS73B', 'PAO');
        //  Product2 product2= HRCFSL_TestUtilityClass.createProduct(true, 'PS73B', 'PAO');
       // Account account = HRCFSL_TestUtilityClass.createAccount(true,'Active');     
    }
    
    @isTest
    static void TestCreateOrderandOLI() {
        try{
              Id recordTypeId = Schema.SObjectType.Order_Line_Item__c.getRecordTypeInfosByName().get('Parts Order Line Item').getRecordTypeId();
            product2 product1 = [select id, name from product2 where name = 'CENTRELLABED1' limit 1];
           // product2  product2 = [select id, name from product2 where ProductCode = 'ABC' limit 1];
            Test.setMock(HttpCalloutMock.class, new HRCSVC21_OLI_Handler_Test());
            Schema.Location loc = [select id from location where HRCFSL_Customer_ID__c = 'Customer1234'];
            order__c ord1 = new Order__c(Name='CG',HRCSVC_ERP_Order_Number__c='CG',Proposal_Date__c=system.today(),
                                         HRCSVC_Proposal_Date__c=system.today(),HRCSVC_Ship_To_Location__c=loc.id,HRCSVC_Patient_First_Name__c='John',HRCSVC_Patient_Last_Name__c='Mrak');
            insert ord1;
            test.startTest();  
            List<Order_Line_Item__c> olisList= new List<Order_Line_Item__c>();
            Order_Line_Item__c oli1 = new Order_Line_Item__c(Order__c=ord1.id,Quantity__c=100,Product__c=product1.id,recordTypeId=recordTypeId);
            Order_Line_Item__c oli2 = new Order_Line_Item__c(Order__c=ord1.id,Quantity__c=130,Product__c=product1.id,recordTypeId=recordTypeId);
            olisList.add(oli1);
            olisList.add(oli2);
            insert olisList;
            oli1.Product__c=null;
            update oli1;
            List<String> oliId= new List<String>();
            oliId.add(oli1.id);
            List<List<String>> oliList= new List<List<String>>();
            oliList.add(oliId);
            HRCSVC21_OLI_Handler.getPricing(oliList);
            oliId.add(oli2.id);
            oliList.add(oliId);
            HRCSVC21_OLI_Handler.getPricing(oliList);
            HRCSVC21_OLI_Handler.getPricing(null);
            HRCSVC21_Get_Pricing.passingIds(null);
            test.stopTest(); 
        }catch(Exception e){
            system.debug('e'+e.getLineNumber()+e.getCause()+e.getStackTraceString());
        }
    }
    
    
}