force-app/main/default/objects/Sales_Goal_Data__c/Sales_Goal_Data__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Sales Goal Data - Data provided by HRC</description>
    <label>Sales Goal Data</label>
    <nameField>
        <displayFormat>SG-{0000000}</displayFormat>
        <label>Sales Goal Data #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Goal Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Goal_Data__c/fields/PK_SALES_GOALS__c.field-meta.xml
<CustomField>
    <fullName>PK_SALES_GOALS__c</fullName>
    <label>PK_SALES_GOALS</label>
    <precision>12</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Goal_Data__c/fields/Sales_User__c.field-meta.xml
<CustomField>
    <fullName>Sales_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the Sales User in Salesforce who the Sales Goal record is associated with. This will be populated by mapping the JDE External ID&apos;s on the Sales Goal and User objects.</description>
    <label>Sales User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Goal_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Goal_Data__c/fields/TERR_CD__c.field-meta.xml
<CustomField>
    <fullName>TERR_CD__c</fullName>
    <label>TERR_CD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HRC_SalesGoalDataControllerTest.cls
@isTest
public class HRC_SalesGoalDataControllerTest
{
    public static testmethod void testSalesGoalData()
    {
        User u = createUser();
        
        Sales_Goal_Data__c sg = new Sales_Goal_Data__c(TERR_CD__c='123', PK_SALES_GOALS__c = 2, Sales_User__c = u.Id);
        insert sg;
        
        System.assert([select Id, OwnerId, Sales_User__c from Sales_Goal_Data__c where Id = :sg.Id limit 1].OwnerId == u.Id);
        
        sg.Sales_User__c = Userinfo.getUserId();
        update sg;
        
        System.assert([select Id, OwnerId, Sales_User__c from Sales_Goal_Data__c where Id = :sg.Id limit 1].OwnerId == Userinfo.getUserId());
    }
    private static User createUser()
    {
        String uniqueKey = '49a84701';
        User testUser ;
        testUser = new User();
        testUser.Alias = uniqueKey;
        testUser.Email = uniqueKey + '@hill-rom.com';
        testUser.EmailEncodingKey = 'UTF-8';
        testUser.LastName = 'Test' + uniqueKey;
        testUser.LanguageLocaleKey = 'en_US';
        testUser.LocaleSidKey = 'en_US';
        testUser.ProfileId = [SELECT Id FROM Profile WHERE Name = 'HRC Account Executive'].Id;
        testUser.TimeZoneSidKey = 'America/Chicago';
        testUser.Username = uniqueKey + 'test' + Math.round(Math.random() * 10000) + '@hill-rom.com';
        testUser.UserRoleId = null;
        testUser.Country = 'United States';
        insert testUser;
        return testUser;
    }
}