force-app/main/default/objects/Account_Record_Type_Ids__c/Account_Record_Type_Ids__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to map JDE Record Types to actual Salesforce.com Account Record Types durring integration</description>
    <label>Account Record Type Ids</label>
</CustomObject>

force-app/main/default/objects/Account_Record_Type_Ids__c/fields/RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId__c</fullName>
    <label>RecordTypeId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAssignAccountRecordTypeFromJDE.cls
@isTest
private class TestAssignAccountRecordTypeFromJDE {

    static testMethod void runTest() {
	  	 Account_Record_Type_Ids__c art 
	  	   = new Account_Record_Type_Ids__c(name = 'FACx',
	  	                                    RecordTypeId__c = [Select Id from RecordType where SObjectType = 'Account' Limit 1].Id );
	  	 insert art;                   
	     
	     Account a = new Account(Name = 'x', JDE_Record_Type__c = 'FACx');
	     try{
	        insert a;
	     }
	     catch(Exception e){}
	  }

}